<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_vCelUCtpEe-GQdByl4qvpg" name="PE01.02_Gestión_de_Calidad_Institucional" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_vCelUStpEe-GQdByl4qvpg" name="Gestión de Calidad Institucional">
      <elements xmi:type="process:Lane" xmi:id="_vCelUitpEe-GQdByl4qvpg" name="Unidad de Calidad Institucional" actor="_9Hv8QC3tEe-AtcusV1AfBQ">
        <elements xmi:type="process:StartEvent" xmi:id="_vCelUytpEe-GQdByl4qvpg" name="Inicio proceso" outgoing="_IG0-ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vCelVCtpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vCelVStpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vCelVitpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_E6JmwCtrEe-GQdByl4qvpg" name="Elaboración, Evaluación, Coordinación y Supervisión del PAMC" outgoing="_OO03ICtrEe-GQdByl4qvpg" incoming="_IG0-ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E6K04StrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E6K04CtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E6K04itrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E6K05StrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E6K05itrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E6K05ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E6K06StrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E6K06CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_E6K04ytrEe-GQdByl4qvpg" name="Elaboración, Evaluación, Coordinación y Supervisión del PAMC" content="Elaboración, Evaluación, Coordinación y Supervisión del PAMC" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_E6K05CtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_JJt-gCtrEe-GQdByl4qvpg" name="Gestion de fondos para la investigacion" outgoing="_Oo5kACtrEe-GQdByl4qvpg" incoming="_OO03ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JJulkStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JJulkCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JJulkitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JJullStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JJullitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JJullytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JJulmStrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JJulmCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_JJulkytrEe-GQdByl4qvpg" name="Informe de Resultado de Satisfacción" content="Informe de Resultado de Satisfacción" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_JJullCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_N2nygCtrEe-GQdByl4qvpg" name="FIn del Proeso" incoming="_Oo5kACtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_N2pAoCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_N2oZkCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_N2pAoStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_vCelZCtpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_A4nu8DXHEe-8VaPSlsePwg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_vCelZitpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_vCelZytpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IG0-ICtrEe-GQdByl4qvpg" target="_E6JmwCtrEe-GQdByl4qvpg" source="_vCelUytpEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IG1lMCtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IG1lMStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OO03ICtrEe-GQdByl4qvpg" target="_JJt-gCtrEe-GQdByl4qvpg" source="_E6JmwCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OO1eMCtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OO1eMStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Oo5kACtrEe-GQdByl4qvpg" target="_N2nygCtrEe-GQdByl4qvpg" source="_JJt-gCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Oo6LECtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Oo6LEStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_9Hv8QC3tEe-AtcusV1AfBQ" name="Director del Vicerrectorado de Investigacion" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_vCelbCtpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelbStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCelbitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCelbytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelcCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCelcStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCelcitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelcytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeldCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeldStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelditpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeldytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeleCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCeleStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeleitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeleytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_0Iom0CtpEe-GQdByl4qvpg" name="Elaboración, Evaluación, Coordinación y Supervisión del PAMC">
      <elements xmi:type="process:Lane" xmi:id="_vqvs8CtuEe-GQdByl4qvpg" name="Secretaria de Oficina" actor="_J4mggDWtEe-uRsJORBwrSA">
        <elements xmi:type="process:StartEvent" xmi:id="_x48xQytrEe-GQdByl4qvpg" name="Elaboración del PAMC" outgoing="_z4Rc4DWsEe-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x48xRCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x48xRStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x48xRitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_m4sJAC4BEe-IB970bJnsFw" name="Coordinadar Departamentos" outgoing="_klrpUDW8Ee-uRsJORBwrSA" incoming="_z4Rc4DWsEe-uRsJORBwrSA" actor="_J4mggDWtEe-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jgyZES4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jgyZEC4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jgyZEi4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_cTP24jWtEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cTP24zWtEe-uRsJORBwrSA" name="actaDeDepartamentos" content="actaDeDepartamentos" type="TYPE_VARIABLE" returnType="com.dexo.model.ActaDeDepartamentos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cTP25DWtEe-uRsJORBwrSA" name="actaDeDepartamentos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.ActaDeDepartamentos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cTP25TWtEe-uRsJORBwrSA" name="actaDeDepartamentosInput.departamentosInvolucrados" content="actaDeDepartamentosInput?.departamentosInvolucrados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cTP25jWtEe-uRsJORBwrSA" name="actaDeDepartamentosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cTP25zWtEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setDepartamentosInvolucrados">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_cTP26DWtEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cTP26TWtEe-uRsJORBwrSA" name="actaDeDepartamentos" content="actaDeDepartamentos" type="TYPE_VARIABLE" returnType="com.dexo.model.ActaDeDepartamentos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cTP26jWtEe-uRsJORBwrSA" name="actaDeDepartamentos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.ActaDeDepartamentos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cTP26zWtEe-uRsJORBwrSA" name="actaDeDepartamentosInput.fechaDeCoordinacion" content="actaDeDepartamentosInput?.fechaDeCoordinacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cTP27DWtEe-uRsJORBwrSA" name="actaDeDepartamentosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cTP27TWtEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaDeCoordinacion">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jgyZEy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jgyZFC4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jgyZFS4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jgyZFy4BEe-IB970bJnsFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jgyZFi4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_m4swGS4BEe-IB970bJnsFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_JJmNcC4CEe-IB970bJnsFw" name="inputasd" content="715f395a-0019-46e5-8345-339ce196ef13" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_m4swGC4BEe-IB970bJnsFw">
            <inputs xmi:type="process:ContractInput" xmi:id="_cTOBsDWtEe-uRsJORBwrSA" name="actaDeDepartamentosInput" type="COMPLEX" dataReference="actaDeDepartamentos" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cTOBsTWtEe-uRsJORBwrSA" name="departamentosInvolucrados" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cTOBsjWtEe-uRsJORBwrSA" name="fechaDeCoordinacion" type="DATE" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cTP24DWtEe-uRsJORBwrSA" expression="actaDeDepartamentosInput?.departamentosInvolucrados != null" errorMessage="departamentosInvolucrados is mandatory for ActaDeDepartamentos" name="mandatory_actaDeDepartamentosInput_departamentosInvolucrados">
              <inputNames>actaDeDepartamentosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cTP24TWtEe-uRsJORBwrSA" expression="actaDeDepartamentosInput?.fechaDeCoordinacion != null" errorMessage="fechaDeCoordinacion is mandatory for ActaDeDepartamentos" name="mandatory_actaDeDepartamentosInput_fechaDeCoordinacion">
              <inputNames>actaDeDepartamentosInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_m4swGy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_agYDIC3uEe-AtcusV1AfBQ" name="Asistente Administrativo" actor="_4gM3ADW8Ee-uRsJORBwrSA">
        <elements xmi:type="process:Task" xmi:id="_mq960DW8Ee-uRsJORBwrSA" name="Elaborar el PAMC" outgoing="_hG4KsDW9Ee-uRsJORBwrSA" incoming="_klrpUDW8Ee-uRsJORBwrSA _PcJY4DW-Ee-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g5baAjW8Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g5baATW8Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g5baAzW8Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_C6qDtzW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C6qDuDW9Ee-uRsJORBwrSA" name="pamc" content="pamc" type="TYPE_VARIABLE" returnType="com.dexo.model.PAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_C6qDuTW9Ee-uRsJORBwrSA" name="pamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.PAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C6qDujW9Ee-uRsJORBwrSA" name="pamcInput.id" content="pamcInput?.id" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_C6qDuzW9Ee-uRsJORBwrSA" name="pamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C6qDvDW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setId">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_C6qDvTW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C6qDvjW9Ee-uRsJORBwrSA" name="pamc" content="pamc" type="TYPE_VARIABLE" returnType="com.dexo.model.PAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_C6qDvzW9Ee-uRsJORBwrSA" name="pamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.PAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C6qDwDW9Ee-uRsJORBwrSA" name="pamcInput.descripcion" content="pamcInput?.descripcion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_C6qDwTW9Ee-uRsJORBwrSA" name="pamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C6qDwjW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setDescripcion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_C6qDwzW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C6qDxDW9Ee-uRsJORBwrSA" name="pamc" content="pamc" type="TYPE_VARIABLE" returnType="com.dexo.model.PAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_C6qDxTW9Ee-uRsJORBwrSA" name="pamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.PAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C6qDxjW9Ee-uRsJORBwrSA" name="pamcInput.fechaInicio" content="pamcInput?.fechaInicio" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_C6qDxzW9Ee-uRsJORBwrSA" name="pamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C6qDyDW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaInicio">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_C6qDyTW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_C6qDyjW9Ee-uRsJORBwrSA" name="pamc" content="pamc" type="TYPE_VARIABLE" returnType="com.dexo.model.PAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_C6qDyzW9Ee-uRsJORBwrSA" name="pamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.PAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_C6qDzDW9Ee-uRsJORBwrSA" name="pamcInput.fechaFin" content="pamcInput?.fechaFin" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_C6qDzTW9Ee-uRsJORBwrSA" name="pamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_C6qDzjW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaFin">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_g5baBDW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_g5baBTW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_g5baBjW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_g5baCDW8Ee-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_g5baBzW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mq962jW8Ee-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_skvxoDW8Ee-uRsJORBwrSA" name="inPAMC" content="f7871157-eafd-437c-84a8-0146cba81d61" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mq962TW8Ee-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_C6qDsDW9Ee-uRsJORBwrSA" name="pamcInput" type="COMPLEX" dataReference="pamc" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_C6qDsTW9Ee-uRsJORBwrSA" name="id" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_C6qDsjW9Ee-uRsJORBwrSA" name="descripcion" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_C6qDszW9Ee-uRsJORBwrSA" name="fechaInicio" type="LOCALDATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_C6qDtDW9Ee-uRsJORBwrSA" name="fechaFin" type="LOCALDATE" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_C6qDtTW9Ee-uRsJORBwrSA" expression="pamcInput?.id != null" errorMessage="id is mandatory for PAMC" name="mandatory_pamcInput_id">
              <inputNames>pamcInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_C6qDtjW9Ee-uRsJORBwrSA" expression="pamcInput?.fechaInicio != null" errorMessage="fechaInicio is mandatory for PAMC" name="mandatory_pamcInput_fechaInicio">
              <inputNames>pamcInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mq963DW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Mjqv4DW-Ee-uRsJORBwrSA" name="Supervisar el PAMC final" outgoing="_heBp-DW-Ee-uRsJORBwrSA" incoming="_OrZRYDW-Ee-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Mj0g4TW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Mj0g4DW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Mj0g4jW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_NTnJpTW_Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_NTnJpjW_Ee-uRsJORBwrSA" name="actaDeDepartamentos" content="actaDeDepartamentos" type="TYPE_VARIABLE" returnType="com.dexo.model.ActaDeDepartamentos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_NTnJpzW_Ee-uRsJORBwrSA" name="actaDeDepartamentos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.ActaDeDepartamentos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_NTnJqDW_Ee-uRsJORBwrSA" name="actaDeDepartamentosInput.departamentosInvolucrados" content="     ?.departamentosInvolucrados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_NTnJqjW_Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setDepartamentosInvolucrados">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_NTnJqzW_Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_NTnJrDW_Ee-uRsJORBwrSA" name="actaDeDepartamentos" content="actaDeDepartamentos" type="TYPE_VARIABLE" returnType="com.dexo.model.ActaDeDepartamentos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_NTnJrTW_Ee-uRsJORBwrSA" name="actaDeDepartamentos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.ActaDeDepartamentos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_NTnJrjW_Ee-uRsJORBwrSA" name="actaDeDepartamentosInput.fechaDeCoordinacion" content="     ?.fechaDeCoordinacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date"/>
            <operator xmi:type="expression:Operator" xmi:id="_NTnJsDW_Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaDeCoordinacion">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ULUBRTW_Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ULUBRjW_Ee-uRsJORBwrSA" name="supervisionDelPamc" content="supervisionDelPamc" type="TYPE_VARIABLE" returnType="com.dexo.model.SupervisionDelPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ULUBRzW_Ee-uRsJORBwrSA" name="supervisionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.SupervisionDelPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ULUBSDW_Ee-uRsJORBwrSA" name="supervisionDelPamcInput.fechaDeSupervision" content="supervisionDelPamcInput?.fechaDeSupervision" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ULUBSTW_Ee-uRsJORBwrSA" name="supervisionDelPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ULUBSjW_Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaDeSupervision">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ULUBSzW_Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ULUBTDW_Ee-uRsJORBwrSA" name="supervisionDelPamc" content="supervisionDelPamc" type="TYPE_VARIABLE" returnType="com.dexo.model.SupervisionDelPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ULUBTTW_Ee-uRsJORBwrSA" name="supervisionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.SupervisionDelPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ULUBTjW_Ee-uRsJORBwrSA" name="supervisionDelPamcInput.detalles" content="supervisionDelPamcInput?.detalles" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ULUBTzW_Ee-uRsJORBwrSA" name="supervisionDelPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ULUBUDW_Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setDetalles">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Mj0g4zW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Mj0g5DW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Mj0g5TW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Mj0g5zW-Ee-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Mj0g5jW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Mj0g6TW-Ee-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_Mj0g6jW-Ee-uRsJORBwrSA" name="inSuper" content="8a423a97-9cdb-4143-acf6-08b327ad5532" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Mj0g6DW-Ee-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_ULUBQDW_Ee-uRsJORBwrSA" name="supervisionDelPamcInput" type="COMPLEX" dataReference="supervisionDelPamc" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ULUBQTW_Ee-uRsJORBwrSA" name="fechaDeSupervision" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_ULUBQjW_Ee-uRsJORBwrSA" name="detalles" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ULUBQzW_Ee-uRsJORBwrSA" expression="supervisionDelPamcInput?.fechaDeSupervision != null" errorMessage="fechaDeSupervision is mandatory for SupervisionDelPAMC" name="mandatory_supervisionDelPamcInput_fechaDeSupervision">
              <inputNames>supervisionDelPamcInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ULUBRDW_Ee-uRsJORBwrSA" expression="supervisionDelPamcInput?.detalles != null" errorMessage="detalles is mandatory for SupervisionDelPAMC" name="mandatory_supervisionDelPamcInput_detalles">
              <inputNames>supervisionDelPamcInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Mj0g6zW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_heBp8DW-Ee-uRsJORBwrSA" name="PAMC realizado" incoming="_heBp-DW-Ee-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_heBp8jW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_heBp8TW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_heBp8zW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fj8DoC3uEe-AtcusV1AfBQ" name="Jefe de Oficina" actor="_45dloC3nEe-pm-hOycnQdg">
        <elements xmi:type="process:Task" xmi:id="_oIdXEDW9Ee-uRsJORBwrSA" name="Evaluar el borrador del PAMC" outgoing="_JrdMqDW-Ee-uRsJORBwrSA" incoming="_hG4KsDW9Ee-uRsJORBwrSA" actor="_p_o7IDW9Ee-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bU6zIjW9Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bU6zITW9Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bU6zIzW9Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s4U_hjW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s4U_hzW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" content="evaluacionDelPamc" type="TYPE_VARIABLE" returnType="com.dexo.model.EvaluacionDelPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s4U_iDW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.EvaluacionDelPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s4U_iTW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput.fechaDeRevision" content="evaluacionDelPamcInput?.fechaDeRevision" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s4U_ijW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s4U_izW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaDeRevision">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s4U_jDW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s4U_jTW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" content="evaluacionDelPamc" type="TYPE_VARIABLE" returnType="com.dexo.model.EvaluacionDelPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s4U_jjW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.EvaluacionDelPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s4U_jzW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput.comentarios" content="evaluacionDelPamcInput?.comentarios" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s4U_kDW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s4U_kTW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setComentarios">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s4U_kjW9Ee-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s4U_kzW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" content="evaluacionDelPamc" type="TYPE_VARIABLE" returnType="com.dexo.model.EvaluacionDelPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s4U_lDW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.EvaluacionDelPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s4U_lTW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput.aprobacion" content="evaluacionDelPamcInput?.aprobacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s4U_ljW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s4U_lzW9Ee-uRsJORBwrSA" type="JAVA_METHOD" expression="setAprobacion">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bU6zJDW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bU6zJTW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bU6zJjW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bU6zKDW9Ee-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bU6zJzW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_oIdXGjW9Ee-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_oIdXGzW9Ee-uRsJORBwrSA" name="inEvaluacion" content="62ed35f9-5efa-4662-8465-ebe796017a2d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_oIdXGTW9Ee-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_s4U_gDW9Ee-uRsJORBwrSA" name="evaluacionDelPamcInput" type="COMPLEX" dataReference="evaluacionDelPamc" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_s4U_gTW9Ee-uRsJORBwrSA" name="fechaDeRevision" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s4U_gjW9Ee-uRsJORBwrSA" name="comentarios" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_s4U_gzW9Ee-uRsJORBwrSA" name="aprobacion" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_s4U_hDW9Ee-uRsJORBwrSA" expression="evaluacionDelPamcInput?.fechaDeRevision != null" errorMessage="fechaDeRevision is mandatory for EvaluacionDelPAMC" name="mandatory_evaluacionDelPamcInput_fechaDeRevision">
              <inputNames>evaluacionDelPamcInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_s4U_hTW9Ee-uRsJORBwrSA" expression="evaluacionDelPamcInput?.aprobacion != null" errorMessage="aprobacion is mandatory for EvaluacionDelPAMC" name="mandatory_evaluacionDelPamcInput_aprobacion">
              <inputNames>evaluacionDelPamcInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_oIdXHDW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_LP8eMDW-Ee-uRsJORBwrSA" name="¿Se aprobo ?" outgoing="_OrZRYDW-Ee-uRsJORBwrSA _PcJY4DW-Ee-uRsJORBwrSA" incoming="_JrdMqDW-Ee-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JrdMojW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JrdMoTW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JrdMozW-Ee-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Uu1qQDWtEe-uRsJORBwrSA" name="actaDeDepartamentos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.ActaDeDepartamentos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Uu1qQTWtEe-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="__rtbcDW8Ee-uRsJORBwrSA" name="pamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.PAMC">
        <defaultValue xmi:type="expression:Expression" xmi:id="__rtbcTW8Ee-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_lGZ7UDW9Ee-uRsJORBwrSA" name="evaluacionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.EvaluacionDelPAMC">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lGZ7UTW9Ee-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_fEauQDW-Ee-uRsJORBwrSA" name="supervisionDelPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.model.SupervisionDelPAMC">
        <defaultValue xmi:type="expression:Expression" xmi:id="_fEauQTW-Ee-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_0IqcDytpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_Az3KwDXHEe-8VaPSlsePwg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_0IrDECtpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_0IrDEStpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z4Rc4DWsEe-uRsJORBwrSA" target="_m4sJAC4BEe-IB970bJnsFw" source="_x48xQytrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z4ZYsDWsEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_z4ZYsTWsEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_klrpUDW8Ee-uRsJORBwrSA" target="_mq960DW8Ee-uRsJORBwrSA" source="_m4sJAC4BEe-IB970bJnsFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_klrpUTW8Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_klrpUjW8Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hG4KsDW9Ee-uRsJORBwrSA" target="_oIdXEDW9Ee-uRsJORBwrSA" source="_mq960DW8Ee-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hG4KsTW9Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hG4KsjW9Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JrdMqDW-Ee-uRsJORBwrSA" target="_LP8eMDW-Ee-uRsJORBwrSA" source="_oIdXEDW9Ee-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JrdMqTW-Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_JrdMqjW-Ee-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OrZRYDW-Ee-uRsJORBwrSA" name="Si" target="_Mjqv4DW-Ee-uRsJORBwrSA" source="_LP8eMDW-Ee-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OrZRYTW-Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_OrZRYjW-Ee-uRsJORBwrSA" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PcJY4DW-Ee-uRsJORBwrSA" name="No" target="_mq960DW8Ee-uRsJORBwrSA" source="_LP8eMDW-Ee-uRsJORBwrSA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PcJY4TW-Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PcJY4jW-Ee-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_heBp-DW-Ee-uRsJORBwrSA" target="_heBp8DW-Ee-uRsJORBwrSA" source="_Mjqv4DW-Ee-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_heBp-TW-Ee-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_heBp-jW-Ee-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_45dloC3nEe-pm-hOycnQdg" name="Director del Vicerrectorado de Investigacion"/>
      <actors xmi:type="process:Actor" xmi:id="_5cZ90C3rEe-AtcusV1AfBQ" name="Analista de Informacion"/>
      <actors xmi:type="process:Actor" xmi:id="_7oA5wC3rEe-AtcusV1AfBQ" name="Responsable de Planificación de I+D+I+E"/>
      <actors xmi:type="process:Actor" xmi:id="_J4mggDWtEe-uRsJORBwrSA" name="Secretaria de Oficina" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_4gM3ADW8Ee-uRsJORBwrSA" name="Asistente Administrativo"/>
      <actors xmi:type="process:Actor" xmi:id="_p_o7IDW9Ee-uRsJORBwrSA" name="Jefe de Oficina"/>
      <contract xmi:type="process:Contract" xmi:id="_0IrDEitpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcACtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcAStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcAitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcAytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcBCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcBStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcBitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcBytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcCCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcCStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcCitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcCytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcDCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcDStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcDitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_3Y3BcCtpEe-GQdByl4qvpg" name="Informe de Resultado de Satisfacción">
      <elements xmi:type="process:Lane" xmi:id="_1VMuUCtuEe-GQdByl4qvpg" name="Coordinador de Unidad de Calidad" actor="_ySL4wDXAEe-uRsJORBwrSA">
        <elements xmi:type="process:StartEvent" xmi:id="_nyXD4DXAEe-uRsJORBwrSA" name="Realización del Informe" outgoing="_rMKRTDXAEe-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nyXD4jXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nyXD4TXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nyXD4zXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vzclcDXAEe-uRsJORBwrSA" name="Implementar Acciones del PAMC" outgoing="_OjYdjDXBEe-uRsJORBwrSA" incoming="_rMKRTDXAEe-uRsJORBwrSA" actor="_ySL4wDXAEe-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rMKRQjXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rMKRQTXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rMKRQzXAEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_IvCgWDXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IvCgWTXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" content="implementacionAccionesPamc" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IvCgWjXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IvCgWzXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput.fechaInicio" content="implementacionAccionesPamcInput?.fechaInicio" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IvCgXDXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IvCgXTXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaInicio">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IvCgXjXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IvCgXzXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" content="implementacionAccionesPamc" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IvCgYDXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IvCgYTXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput.accionesAImplementar" content="implementacionAccionesPamcInput?.accionesAImplementar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IvCgYjXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IvCgYzXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setAccionesAImplementar">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IvCgZDXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IvCgZTXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" content="implementacionAccionesPamc" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IvCgZjXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IvCgZzXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput.responsables" content="implementacionAccionesPamcInput?.responsables" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IvCgaDXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IvCgaTXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setResponsables">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_IvCgajXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IvCgazXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" content="implementacionAccionesPamc" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IvCgbDXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IvCgbTXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput.comentarios" content="implementacionAccionesPamcInput?.comentarios" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_IvCgbjXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IvCgbzXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setComentarios">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rMKRRDXAEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rMKRRTXAEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rMKRRjXAEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rMKRSDXAEe-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rMKRRzXAEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vzclejXAEe-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_JpbsADXBEe-uRsJORBwrSA" name="inSatImplementacion" content="23c44ec7-920a-4877-acec-a0e8f4ae1bd2" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vzcleTXAEe-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_IvCgUDXBEe-uRsJORBwrSA" name="implementacionAccionesPamcInput" type="COMPLEX" dataReference="implementacionAccionesPamc" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_IvCgUTXBEe-uRsJORBwrSA" name="fechaInicio" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IvCgUjXBEe-uRsJORBwrSA" name="accionesAImplementar" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IvCgUzXBEe-uRsJORBwrSA" name="responsables" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_IvCgVDXBEe-uRsJORBwrSA" name="comentarios" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_IvCgVTXBEe-uRsJORBwrSA" expression="implementacionAccionesPamcInput?.fechaInicio != null" errorMessage="fechaInicio is mandatory for ImplementacionAccionesPAMC" name="mandatory_implementacionAccionesPamcInput_fechaInicio">
              <inputNames>implementacionAccionesPamcInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_IvCgVjXBEe-uRsJORBwrSA" expression="implementacionAccionesPamcInput?.accionesAImplementar != null" errorMessage="accionesAImplementar is mandatory for ImplementacionAccionesPAMC" name="mandatory_implementacionAccionesPamcInput_accionesAImplementar">
              <inputNames>implementacionAccionesPamcInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_IvCgVzXBEe-uRsJORBwrSA" expression="implementacionAccionesPamcInput?.responsables != null" errorMessage="responsables is mandatory for ImplementacionAccionesPAMC" name="mandatory_implementacionAccionesPamcInput_responsables">
              <inputNames>implementacionAccionesPamcInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vzclfDXAEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_T6xysC3vEe-AtcusV1AfBQ" name="Asistente Administrativo" actor="_VWo6ADXBEe-uRsJORBwrSA">
        <elements xmi:type="process:Task" xmi:id="_Qzb0kDXBEe-uRsJORBwrSA" name="Recolectar Datos de Satisfacción" outgoing="_hnSzWDXBEe-uRsJORBwrSA" incoming="_OjYdjDXBEe-uRsJORBwrSA _45j_8DXBEe-uRsJORBwrSA" actor="_VWo6ADXBEe-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OjYdgjXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OjYdgTXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OjYdgzXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_cA0TCTXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cA0TCjXBEe-uRsJORBwrSA" name="recoleccionDatos" content="recoleccionDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.RecoleccionDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cA0TCzXBEe-uRsJORBwrSA" name="recoleccionDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.RecoleccionDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cA0TDDXBEe-uRsJORBwrSA" name="recoleccionDatosInput.fechaRecoleccion" content="recoleccionDatosInput?.fechaRecoleccion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cA0TDTXBEe-uRsJORBwrSA" name="recoleccionDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cA0TDjXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaRecoleccion">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_cA0TDzXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cA0TEDXBEe-uRsJORBwrSA" name="recoleccionDatos" content="recoleccionDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.RecoleccionDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cA0TETXBEe-uRsJORBwrSA" name="recoleccionDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.RecoleccionDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cA0TEjXBEe-uRsJORBwrSA" name="recoleccionDatosInput.metodoRecoleccion" content="recoleccionDatosInput?.metodoRecoleccion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cA0TEzXBEe-uRsJORBwrSA" name="recoleccionDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cA0TFDXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setMetodoRecoleccion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_cA0TFTXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cA0TFjXBEe-uRsJORBwrSA" name="recoleccionDatos" content="recoleccionDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.RecoleccionDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cA0TFzXBEe-uRsJORBwrSA" name="recoleccionDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.RecoleccionDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cA0TGDXBEe-uRsJORBwrSA" name="recoleccionDatosInput.comentarios" content="recoleccionDatosInput?.comentarios" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cA0TGTXBEe-uRsJORBwrSA" name="recoleccionDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cA0TGjXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setComentarios">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_cA0TGzXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cA0THDXBEe-uRsJORBwrSA" name="recoleccionDatos" content="recoleccionDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.RecoleccionDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cA0THTXBEe-uRsJORBwrSA" name="recoleccionDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.RecoleccionDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cA0THjXBEe-uRsJORBwrSA" name="recoleccionDatosInput.documentosAdjuntos" content="recoleccionDatosInput?.documentosAdjuntos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cA0THzXBEe-uRsJORBwrSA" name="recoleccionDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cA0TIDXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setDocumentosAdjuntos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OjYdhDXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OjYdhTXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OjYdhjXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OjYdiDXBEe-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OjYdhzXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Qzb0mjXBEe-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_Qzb0mzXBEe-uRsJORBwrSA" name="inSatRecoleccion" content="15f02112-c960-4e9e-b9cd-d79f722f0331" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Qzb0mTXBEe-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_cA0TADXBEe-uRsJORBwrSA" name="recoleccionDatosInput" type="COMPLEX" dataReference="recoleccionDatos" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cA0TATXBEe-uRsJORBwrSA" name="fechaRecoleccion" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cA0TAjXBEe-uRsJORBwrSA" name="metodoRecoleccion" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cA0TAzXBEe-uRsJORBwrSA" name="comentarios" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cA0TBDXBEe-uRsJORBwrSA" name="documentosAdjuntos" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cA0TBTXBEe-uRsJORBwrSA" expression="recoleccionDatosInput?.fechaRecoleccion != null" errorMessage="fechaRecoleccion is mandatory for RecoleccionDatos" name="mandatory_recoleccionDatosInput_fechaRecoleccion">
              <inputNames>recoleccionDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cA0TBjXBEe-uRsJORBwrSA" expression="recoleccionDatosInput?.metodoRecoleccion != null" errorMessage="metodoRecoleccion is mandatory for RecoleccionDatos" name="mandatory_recoleccionDatosInput_metodoRecoleccion">
              <inputNames>recoleccionDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cA0TBzXBEe-uRsJORBwrSA" expression="recoleccionDatosInput?.comentarios != null" errorMessage="comentarios is mandatory for RecoleccionDatos" name="mandatory_recoleccionDatosInput_comentarios">
              <inputNames>recoleccionDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cA0TCDXBEe-uRsJORBwrSA" expression="recoleccionDatosInput?.documentosAdjuntos != null" errorMessage="documentosAdjuntos is mandatory for RecoleccionDatos" name="mandatory_recoleccionDatosInput_documentosAdjuntos">
              <inputNames>recoleccionDatosInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Qzb0nDXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_i1YXEDXBEe-uRsJORBwrSA" name="Compuerta1" outgoing="_j1JK_DXBEe-uRsJORBwrSA _45j_8DXBEe-uRsJORBwrSA" incoming="_hnSzWDXBEe-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hnSzUjXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hnSzUTXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hnSzUzXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_BkjaIDXCEe-uRsJORBwrSA" name="Realizar Informe de Resultados de Satisfacción" outgoing="_GS9qADXCEe-uRsJORBwrSA" incoming="_-uWpEzXBEe-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-uM4EjXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-uM4ETXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-uM4EzXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_MyIs6TXCEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_MyIs6jXCEe-uRsJORBwrSA" name="informeDatos" content="informeDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.InformeDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MyIs6zXCEe-uRsJORBwrSA" name="informeDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.InformeDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_MyIs7DXCEe-uRsJORBwrSA" name="informeDatosInput.fechaInforme" content="informeDatosInput?.fechaInforme" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_MyIs7TXCEe-uRsJORBwrSA" name="informeDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_MyIs7jXCEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaInforme">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_MyIs7zXCEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_MyIs8DXCEe-uRsJORBwrSA" name="informeDatos" content="informeDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.InformeDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MyIs8TXCEe-uRsJORBwrSA" name="informeDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.InformeDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_MyIs8jXCEe-uRsJORBwrSA" name="informeDatosInput.resumenResultados" content="informeDatosInput?.resumenResultados" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_MyIs8zXCEe-uRsJORBwrSA" name="informeDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_MyIs9DXCEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setResumenResultados">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_MyIs9TXCEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_MyIs9jXCEe-uRsJORBwrSA" name="informeDatos" content="informeDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.InformeDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MyIs9zXCEe-uRsJORBwrSA" name="informeDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.InformeDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_MyIs-DXCEe-uRsJORBwrSA" name="informeDatosInput.recomendaciones" content="informeDatosInput?.recomendaciones" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_MyIs-TXCEe-uRsJORBwrSA" name="informeDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_MyIs-jXCEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setRecomendaciones">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_MyIs-zXCEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_MyIs_DXCEe-uRsJORBwrSA" name="informeDatos" content="informeDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.InformeDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MyIs_TXCEe-uRsJORBwrSA" name="informeDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.InformeDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_MyIs_jXCEe-uRsJORBwrSA" name="informeDatosInput.documentoAdjunto" content="informeDatosInput?.documentoAdjunto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_MyIs_zXCEe-uRsJORBwrSA" name="informeDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_MyItADXCEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setDocumentoAdjunto">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-uM4FDXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-uM4FTXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-uM4FjXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-uM4GDXBEe-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-uM4FzXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BkjaKjXCEe-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_BkjaKzXCEe-uRsJORBwrSA" name="inpSatInforme" content="11f1ab74-8417-4501-8e15-751858bb6340" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BkjaKTXCEe-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_MyIs4DXCEe-uRsJORBwrSA" name="informeDatosInput" type="COMPLEX" dataReference="informeDatos" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_MyIs4TXCEe-uRsJORBwrSA" name="fechaInforme" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_MyIs4jXCEe-uRsJORBwrSA" name="resumenResultados" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_MyIs4zXCEe-uRsJORBwrSA" name="recomendaciones" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_MyIs5DXCEe-uRsJORBwrSA" name="documentoAdjunto" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_MyIs5TXCEe-uRsJORBwrSA" expression="informeDatosInput?.fechaInforme != null" errorMessage="fechaInforme is mandatory for InformeDatos" name="mandatory_informeDatosInput_fechaInforme">
              <inputNames>informeDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_MyIs5jXCEe-uRsJORBwrSA" expression="informeDatosInput?.resumenResultados != null" errorMessage="resumenResultados is mandatory for InformeDatos" name="mandatory_informeDatosInput_resumenResultados">
              <inputNames>informeDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_MyIs5zXCEe-uRsJORBwrSA" expression="informeDatosInput?.recomendaciones != null" errorMessage="recomendaciones is mandatory for InformeDatos" name="mandatory_informeDatosInput_recomendaciones">
              <inputNames>informeDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_MyIs6DXCEe-uRsJORBwrSA" expression="informeDatosInput?.documentoAdjunto != null" errorMessage="documentoAdjunto is mandatory for InformeDatos" name="mandatory_informeDatosInput_documentoAdjunto">
              <inputNames>informeDatosInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BkjaLDXCEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_GS0gEDXCEe-uRsJORBwrSA" name="Informe Realizado" incoming="_GS9qADXCEe-uRsJORBwrSA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GS0gEjXCEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GS0gETXCEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GS0gEzXCEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_UX3XUC3vEe-AtcusV1AfBQ" name="Jefe de Oficina" actor="_r1eekDXBEe-uRsJORBwrSA">
        <elements xmi:type="process:Task" xmi:id="_lc2IkDXBEe-uRsJORBwrSA" name="Analizar Datos de Satisfacción" outgoing="_-uWpEzXBEe-uRsJORBwrSA" incoming="_j1JK_DXBEe-uRsJORBwrSA" actor="_r1eekDXBEe-uRsJORBwrSA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j1JK8jXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j1JK8TXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j1JK8zXBEe-uRsJORBwrSA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_wqIgZTXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wqIgZjXBEe-uRsJORBwrSA" name="analisisDatos" content="analisisDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.AnalisisDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wqIgZzXBEe-uRsJORBwrSA" name="analisisDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.AnalisisDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wqIgaDXBEe-uRsJORBwrSA" name="analisisDatosInput.fechaAnalisis" content="analisisDatosInput?.fechaAnalisis" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wqIgaTXBEe-uRsJORBwrSA" name="analisisDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wqIgajXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setFechaAnalisis">
              <inputTypes>java.util.Date</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_wqIgazXBEe-uRsJORBwrSA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_wqIgbDXBEe-uRsJORBwrSA" name="analisisDatos" content="analisisDatos" type="TYPE_VARIABLE" returnType="com.company.resultadosSatisfaccion.AnalisisDatos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wqIgbTXBEe-uRsJORBwrSA" name="analisisDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.AnalisisDatos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_wqIgbjXBEe-uRsJORBwrSA" name="analisisDatosInput.resultadosAnalisis" content="analisisDatosInput?.resultadosAnalisis" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wqIgbzXBEe-uRsJORBwrSA" name="analisisDatosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_wqIgcDXBEe-uRsJORBwrSA" type="JAVA_METHOD" expression="setResultadosAnalisis">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j1JK9DXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j1JK9TXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j1JK9jXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j1JK-DXBEe-uRsJORBwrSA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j1JK9zXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_lc2ImjXBEe-uRsJORBwrSA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lc2ImzXBEe-uRsJORBwrSA" name="inpSatAnalisis" content="8ff74f23-5ef1-4776-81e8-ce5950f6968b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_lc2ImTXBEe-uRsJORBwrSA">
            <inputs xmi:type="process:ContractInput" xmi:id="_wqIgYDXBEe-uRsJORBwrSA" name="analisisDatosInput" type="COMPLEX" dataReference="analisisDatos" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_wqIgYTXBEe-uRsJORBwrSA" name="fechaAnalisis" type="DATE" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_wqIgYjXBEe-uRsJORBwrSA" name="resultadosAnalisis" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_wqIgYzXBEe-uRsJORBwrSA" expression="analisisDatosInput?.fechaAnalisis != null" errorMessage="fechaAnalisis is mandatory for AnalisisDatos" name="mandatory_analisisDatosInput_fechaAnalisis">
              <inputNames>analisisDatosInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_wqIgZDXBEe-uRsJORBwrSA" expression="analisisDatosInput?.resultadosAnalisis != null" errorMessage="resultadosAnalisis is mandatory for AnalisisDatos" name="mandatory_analisisDatosInput_resultadosAnalisis">
              <inputNames>analisisDatosInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_lc2InDXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Gr8AIDXBEe-uRsJORBwrSA" name="implementacionAccionesPamc" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.ImplementacionAccionesPAMC">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Gr8AITXBEe-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ajHl8DXBEe-uRsJORBwrSA" name="recoleccionDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.RecoleccionDatos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ajHl8TXBEe-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_vAzyIDXBEe-uRsJORBwrSA" name="analisisDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.AnalisisDatos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vAzyITXBEe-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_K4ayMDXCEe-uRsJORBwrSA" name="informeDatos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.company.resultadosSatisfaccion.InformeDatos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_K4ayMTXCEe-uRsJORBwrSA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_3Y4PlStpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_AjBSYDXHEe-8VaPSlsePwg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_3Y4PlytpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_3Y4PmCtpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rMKRTDXAEe-uRsJORBwrSA" target="_vzclcDXAEe-uRsJORBwrSA" source="_nyXD4DXAEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rMKRTTXAEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_rMKRTjXAEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OjYdjDXBEe-uRsJORBwrSA" target="_Qzb0kDXBEe-uRsJORBwrSA" source="_vzclcDXAEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OjYdjTXBEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_OjYdjjXBEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hnSzWDXBEe-uRsJORBwrSA" target="_i1YXEDXBEe-uRsJORBwrSA" source="_Qzb0kDXBEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hnSzWTXBEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hnSzWjXBEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j1JK_DXBEe-uRsJORBwrSA" name="Si" target="_lc2IkDXBEe-uRsJORBwrSA" source="_i1YXEDXBEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j1JK_TXBEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_j1JK_jXBEe-uRsJORBwrSA" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_45j_8DXBEe-uRsJORBwrSA" name="No" target="_Qzb0kDXBEe-uRsJORBwrSA" source="_i1YXEDXBEe-uRsJORBwrSA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_45j_8TXBEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_45j_8jXBEe-uRsJORBwrSA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-uWpEzXBEe-uRsJORBwrSA" target="_BkjaIDXCEe-uRsJORBwrSA" source="_lc2IkDXBEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-uWpFDXBEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_-uWpFTXBEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GS9qADXCEe-uRsJORBwrSA" target="_GS0gEDXCEe-uRsJORBwrSA" source="_BkjaIDXCEe-uRsJORBwrSA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GS9qATXCEe-uRsJORBwrSA"/>
        <condition xmi:type="expression:Expression" xmi:id="_GS9qAjXCEe-uRsJORBwrSA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_apIPIC3xEe-AtcusV1AfBQ" name="Responsable de Gestión de Fondos"/>
      <actors xmi:type="process:Actor" xmi:id="_hatQoC3xEe-AtcusV1AfBQ" name="Director Vicerrectorado"/>
      <actors xmi:type="process:Actor" xmi:id="_idoGMC3xEe-AtcusV1AfBQ" name="Gestor de Relaciones Externas"/>
      <actors xmi:type="process:Actor" xmi:id="_jf7QsC3xEe-AtcusV1AfBQ" name="Coordinador de Proyectos"/>
      <actors xmi:type="process:Actor" xmi:id="_ySL4wDXAEe-uRsJORBwrSA" name="Coordinador de Unidad de Calidad" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_VWo6ADXBEe-uRsJORBwrSA" name="Asistente Administrativo"/>
      <actors xmi:type="process:Actor" xmi:id="_r1eekDXBEe-uRsJORBwrSA" name="Jefe de Oficina"/>
      <contract xmi:type="process:Contract" xmi:id="_3Y4PmStpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ogCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ogStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3ogitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ogytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ohCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3ohStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ohitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ohytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3oiCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3oiStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y4PkCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y4PkStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y4PkitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y4PkytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y4PlCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_vCelfCtpEe-GQdByl4qvpg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_vCelfStpEe-GQdByl4qvpg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_vCelfitpEe-GQdByl4qvpg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_vCelfytpEe-GQdByl4qvpg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_vCelgCtpEe-GQdByl4qvpg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_vCelgStpEe-GQdByl4qvpg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_vCelgitpEe-GQdByl4qvpg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_vCelgytpEe-GQdByl4qvpg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_vCelhCtpEe-GQdByl4qvpg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_vCelhStpEe-GQdByl4qvpg" type="Process" element="_vCelUCtpEe-GQdByl4qvpg" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_vCelhitpEe-GQdByl4qvpg" type="2007" element="_vCelUStpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_vCelhytpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_vCeliCtpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_vCeliStpEe-GQdByl4qvpg" type="3007" element="_vCelUitpEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_vCeliitpEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vCeliytpEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_vCeljytpEe-GQdByl4qvpg" type="3002" element="_vCelUytpEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_vCelkCtpEe-GQdByl4qvpg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vCelkStpEe-GQdByl4qvpg" x="3" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCelkitpEe-GQdByl4qvpg" x="156" y="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E6PGUCtrEe-GQdByl4qvpg" type="3063" element="_E6JmwCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E6PtYCtrEe-GQdByl4qvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E6PGUStrEe-GQdByl4qvpg" x="309" y="56" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JJvzsCtrEe-GQdByl4qvpg" type="3063" element="_JJt-gCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JJwawCtrEe-GQdByl4qvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JJvzsStrEe-GQdByl4qvpg" x="631" y="46" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N2rc4CtrEe-GQdByl4qvpg" type="3003" element="_N2nygCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_N2sD8CtrEe-GQdByl4qvpg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_N2sD8StrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N2rc4StrEe-GQdByl4qvpg" x="956" y="85"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vCelkytpEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vCellCtpEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vCellStpEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vCellitpEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCellytpEe-GQdByl4qvpg" x="48" y="10" width="1227" height="218"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_vCelmCtpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_vCelmStpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_vCelmitpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_vCelmytpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCelnCtpEe-GQdByl4qvpg" width="1250" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_0IsRMCtpEe-GQdByl4qvpg" type="2007" element="_0Iom0CtpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Is4QCtpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0Is4QStpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_vqxiICtuEe-GQdByl4qvpg" type="3007" element="_vqvs8CtuEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_vqyJMCtuEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vqyJMStuEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_x48xRytrEe-GQdByl4qvpg" type="3002" element="_x48xQytrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_x48xSCtrEe-GQdByl4qvpg" type="5024" element="_x48xQytrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_x48xSStrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x48xSitrEe-GQdByl4qvpg" x="104" y="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m4tXIC4BEe-IB970bJnsFw" type="3005" element="_m4sJAC4BEe-IB970bJnsFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_m4tXIi4BEe-IB970bJnsFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m4tXIS4BEe-IB970bJnsFw" x="368" y="56" width="132" height="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vqxiIStuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vqxiIituEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vqxiIytuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vqyJMituEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vqxiJCtuEe-GQdByl4qvpg" x="48" y="10" width="1213" height="235"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_agYqMC3uEe-AtcusV1AfBQ" type="3007" element="_agYDIC3uEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_agZRQC3uEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_agZRQS3uEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_mq963TW8Ee-uRsJORBwrSA" type="3005" element="_mq960DW8Ee-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mq963zW8Ee-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mq963jW8Ee-uRsJORBwrSA" x="346" y="49" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Mj0g7DW-Ee-uRsJORBwrSA" type="3005" element="_Mjqv4DW-Ee-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Mj0g7jW-Ee-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Mj0g7TW-Ee-uRsJORBwrSA" x="742" y="49" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_heBp9DW-Ee-uRsJORBwrSA" type="3003" element="_heBp8DW-Ee-uRsJORBwrSA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_heBp9jW-Ee-uRsJORBwrSA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_heBp9zW-Ee-uRsJORBwrSA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_heBp9TW-Ee-uRsJORBwrSA" x="1001" y="64"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_agYqMS3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_agYqMi3uEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_agYqMy3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_agZRQi3uEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_agYqNC3uEe-AtcusV1AfBQ" x="48" y="235" width="1213" height="190"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fj940C3uEe-AtcusV1AfBQ" type="3007" element="_fj8DoC3uEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_fj941S3uEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fj941i3uEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_oIdXHTW9Ee-uRsJORBwrSA" type="3005" element="_oIdXEDW9Ee-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oIdXHzW9Ee-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oIdXHjW9Ee-uRsJORBwrSA" x="327" y="45" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LP8eNDW-Ee-uRsJORBwrSA" type="3008" element="_LP8eMDW-Ee-uRsJORBwrSA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LP8eNjW-Ee-uRsJORBwrSA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LP8eNzW-Ee-uRsJORBwrSA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LP8eNTW-Ee-uRsJORBwrSA" x="595" y="56" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fj940S3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fj940i3uEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fj940y3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fj941y3uEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fj941C3uEe-AtcusV1AfBQ" x="48" y="460" width="1213" height="193"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0IsRMStpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0IsRMitpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0IsRMytpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0Is4QitpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0IsRNCtpEe-GQdByl4qvpg" width="1236" height="474"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_3Y7S4CtpEe-GQdByl4qvpg" type="2007" element="_3Y3BcCtpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_3Y758CtpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_3Y758StpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_1VN8cCtuEe-GQdByl4qvpg" type="3007" element="_1VMuUCtuEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_1VOjgCtuEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_1VOjgStuEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_nyXD5DXAEe-uRsJORBwrSA" type="3002" element="_nyXD4DXAEe-uRsJORBwrSA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nyXD5jXAEe-uRsJORBwrSA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nyXD5zXAEe-uRsJORBwrSA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nyXD5TXAEe-uRsJORBwrSA" x="134" y="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vzclfTXAEe-uRsJORBwrSA" type="3005" element="_vzclcDXAEe-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vzclfzXAEe-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vzclfjXAEe-uRsJORBwrSA" x="260" y="71" width="154" height="76"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_1VN8cStuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_1VN8cituEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_1VN8cytuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_1VOjgituEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1VN8dCtuEe-GQdByl4qvpg" x="48" y="10" width="1175" height="204"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_T6zA0C3vEe-AtcusV1AfBQ" type="3007" element="_T6xysC3vEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_T6zA1S3vEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_T6zA1i3vEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Qzb0nTXBEe-uRsJORBwrSA" type="3005" element="_Qzb0kDXBEe-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Qzb0nzXBEe-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Qzb0njXBEe-uRsJORBwrSA" x="267" y="73" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_i1YXFDXBEe-uRsJORBwrSA" type="3008" element="_i1YXEDXBEe-uRsJORBwrSA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_i1YXFjXBEe-uRsJORBwrSA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_i1YXFzXBEe-uRsJORBwrSA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i1YXFTXBEe-uRsJORBwrSA" x="512" y="81" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BkjaLTXCEe-uRsJORBwrSA" type="3005" element="_BkjaIDXCEe-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BkjaLzXCEe-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BkjaLjXCEe-uRsJORBwrSA" x="803" y="85" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GS0gFDXCEe-uRsJORBwrSA" type="3003" element="_GS0gEDXCEe-uRsJORBwrSA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GS0gFjXCEe-uRsJORBwrSA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GS0gFzXCEe-uRsJORBwrSA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GS0gFTXCEe-uRsJORBwrSA" x="1045" y="99"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_T6zA0S3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_T6zA0i3vEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_T6zA0y3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_T6zA1y3vEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_T6zA1C3vEe-AtcusV1AfBQ" x="48" y="204" width="1175" height="231"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_UX5MgC3vEe-AtcusV1AfBQ" type="3007" element="_UX3XUC3vEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_UX5MhS3vEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_UX5zkC3vEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_lc2InTXBEe-uRsJORBwrSA" type="3005" element="_lc2IkDXBEe-uRsJORBwrSA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lc2InzXBEe-uRsJORBwrSA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lc2InjXBEe-uRsJORBwrSA" x="593" y="87" width="160" height="80"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_UX5MgS3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_UX5Mgi3vEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_UX5Mgy3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_UX5zkS3vEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UX5MhC3vEe-AtcusV1AfBQ" x="48" y="394" width="1175" height="227"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_3Y7S4StpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_3Y7S4itpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_3Y7S4ytpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_3Y758itpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3Y7S5CtpEe-GQdByl4qvpg" width="1198" height="477"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_vCelnStpEe-GQdByl4qvpg"/>
    <edges xmi:type="notation:Connector" xmi:id="_IG4BcCtrEe-GQdByl4qvpg" type="4001" element="_IG0-ICtrEe-GQdByl4qvpg" source="_vCeljytpEe-GQdByl4qvpg" target="_E6PGUCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IG4ogCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IG4ogStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IG4BcStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IG4BcitrEe-GQdByl4qvpg" points="[-8, -3, -226, -65]$[212, 100, -6, 38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IG9hACtrEe-GQdByl4qvpg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OO2sUCtrEe-GQdByl4qvpg" type="4001" element="_OO03ICtrEe-GQdByl4qvpg" source="_E6PGUCtrEe-GQdByl4qvpg" target="_JJvzsCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OO3TYCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OO3TYStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OO2sUStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OO2sUitrEe-GQdByl4qvpg" points="[0, 9, -256, 0]$[294, 18, 38, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OO69wCtrEe-GQdByl4qvpg" id="(1.0,0.39473684210526316)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OO7k0CtrEe-GQdByl4qvpg" id="(0.7888888888888889,0.6444444444444445)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Oo7ZMCtrEe-GQdByl4qvpg" type="4001" element="_Oo5kACtrEe-GQdByl4qvpg" source="_JJvzsCtrEe-GQdByl4qvpg" target="_N2rc4CtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Oo8AQCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Oo8AQStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Oo7ZMStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Oo7ZMitrEe-GQdByl4qvpg" points="[0, 0, -187, -35]$[185, 20, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Oo_qoCtrEe-GQdByl4qvpg" id="(1.0,0.34444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_z4ffUDWsEe-uRsJORBwrSA" type="4001" element="_z4Rc4DWsEe-uRsJORBwrSA" source="_x48xRytrEe-GQdByl4qvpg" target="_m4tXIC4BEe-IB970bJnsFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z4iioDWsEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z4iioTWsEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z4ffUTWsEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z4ffUjWsEe-uRsJORBwrSA" points="[-8, 0, -352, 28]$[410, -20, 66, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_z4ll8DWsEe-uRsJORBwrSA" id="(1.0,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_klrpUzW8Ee-uRsJORBwrSA" type="4001" element="_klrpUDW8Ee-uRsJORBwrSA" source="_m4tXIC4BEe-IB970bJnsFw" target="_mq963TW8Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_klrpVjW8Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_klrpVzW8Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_klrpVDW8Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_klrpVTW8Ee-uRsJORBwrSA" points="[-15, 36, 89, -213]$[-101, 224, 3, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_klrpWDW8Ee-uRsJORBwrSA" id="(1.0,0.45454545454545453)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hG4KszW9Ee-uRsJORBwrSA" type="4001" element="_hG4KsDW9Ee-uRsJORBwrSA" source="_mq963TW8Ee-uRsJORBwrSA" target="_oIdXHTW9Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hG4KtjW9Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hG4KtzW9Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hG4KtDW9Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hG4KtTW9Ee-uRsJORBwrSA" points="[-53, 20, 6, -255]$[-53, 245, 6, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hHB7sDW9Ee-uRsJORBwrSA" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JrdMqzW-Ee-uRsJORBwrSA" type="4001" element="_JrdMqDW-Ee-uRsJORBwrSA" source="_oIdXHTW9Ee-uRsJORBwrSA" target="_LP8eNDW-Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JrdMrjW-Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JrdMrzW-Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JrdMrDW-Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JrdMrTW-Ee-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OrZRYzW-Ee-uRsJORBwrSA" type="4001" element="_OrZRYDW-Ee-uRsJORBwrSA" source="_LP8eNDW-Ee-uRsJORBwrSA" target="_Mj0g7DW-Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OrZRZjW-Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OrZRZzW-Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OrZRZDW-Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OrZRZTW-Ee-uRsJORBwrSA" points="[0, -6, -164, 167]$[149, -6, -15, 167]$[149, -143, -15, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OrZRaDW-Ee-uRsJORBwrSA" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PcTJ4DW-Ee-uRsJORBwrSA" type="4001" element="_PcJY4DW-Ee-uRsJORBwrSA" source="_LP8eNDW-Ee-uRsJORBwrSA" target="_mq963TW8Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PcTJ4zW-Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PcTJ5DW-Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PcTJ4TW-Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PcTJ4jW-Ee-uRsJORBwrSA" points="[-25, -28, 206, 251]$[-25, -292, 206, -13]$[-192, -292, 39, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PcTJ5TW-Ee-uRsJORBwrSA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PcTJ5jW-Ee-uRsJORBwrSA" id="(0.61,0.76)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_heBp-zW-Ee-uRsJORBwrSA" type="4001" element="_heBp-DW-Ee-uRsJORBwrSA" source="_Mj0g7DW-Ee-uRsJORBwrSA" target="_heBp9DW-Ee-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_heBp_jW-Ee-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_heBp_zW-Ee-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_heBp_DW-Ee-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_heBp_TW-Ee-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rMKRTzXAEe-uRsJORBwrSA" type="4001" element="_rMKRTDXAEe-uRsJORBwrSA" source="_nyXD5DXAEe-uRsJORBwrSA" target="_vzclfTXAEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rMKRUjXAEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rMKRUzXAEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rMKRUDXAEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rMKRUTXAEe-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OjYdjzXBEe-uRsJORBwrSA" type="4001" element="_OjYdjDXBEe-uRsJORBwrSA" source="_vzclfTXAEe-uRsJORBwrSA" target="_Qzb0nTXBEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OjYdkjXBEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OjYdkzXBEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OjYdkDXBEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OjYdkTXBEe-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hnSzWzXBEe-uRsJORBwrSA" type="4001" element="_hnSzWDXBEe-uRsJORBwrSA" source="_Qzb0nTXBEe-uRsJORBwrSA" target="_i1YXFDXBEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hnSzXjXBEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hnSzXzXBEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hnSzXDXBEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hnSzXTXBEe-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j1JK_zXBEe-uRsJORBwrSA" type="4001" element="_j1JK_DXBEe-uRsJORBwrSA" source="_i1YXFDXBEe-uRsJORBwrSA" target="_lc2InTXBEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j1JLAjXBEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j1JLAzXBEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j1JLADXBEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j1JLATXBEe-uRsJORBwrSA" points="[22, 0, -101, -206]$[116, 0, -7, -206]$[116, 175, -7, -31]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_45tJ4DXBEe-uRsJORBwrSA" type="4001" element="_45j_8DXBEe-uRsJORBwrSA" source="_i1YXFDXBEe-uRsJORBwrSA" target="_Qzb0nTXBEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_45tJ4zXBEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_45tJ5DXBEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_45tJ4TXBEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_45tJ4jXBEe-uRsJORBwrSA" points="[-22, 9, 204, 20]$[-22, 55, 204, 66]$[-226, 55, 0, 66]$[-226, 20, 0, 31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_45264DXBEe-uRsJORBwrSA" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-uWpFjXBEe-uRsJORBwrSA" type="4001" element="_-uWpEzXBEe-uRsJORBwrSA" source="_lc2InTXBEe-uRsJORBwrSA" target="_BkjaLTXCEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-uWpGTXBEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-uWpGjXBEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-uWpFzXBEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-uWpGDXBEe-uRsJORBwrSA" points="[63, 6, -168, 180]$[203, 6, -28, 180]$[203, -172, -28, 2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AETvYDXCEe-uRsJORBwrSA" id="(0.83,0.96)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GS9qAzXCEe-uRsJORBwrSA" type="4001" element="_GS9qADXCEe-uRsJORBwrSA" source="_BkjaLTXCEe-uRsJORBwrSA" target="_GS0gFDXCEe-uRsJORBwrSA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GS9qBjXCEe-uRsJORBwrSA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GS9qBzXCEe-uRsJORBwrSA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GS9qBDXCEe-uRsJORBwrSA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GS9qBTXCEe-uRsJORBwrSA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
