<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_vCelUCtpEe-GQdByl4qvpg" name="PM02.01PlanificacionI+D+i+e" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_vCelUStpEe-GQdByl4qvpg" name="PlanificacionI+D+i+e">
      <elements xmi:type="process:Lane" xmi:id="_vCelUitpEe-GQdByl4qvpg" name="Vicerrectorado de Investifacion" actor="_9Hv8QC3tEe-AtcusV1AfBQ">
        <elements xmi:type="process:StartEvent" xmi:id="_vCelUytpEe-GQdByl4qvpg" name="Inicio proceso" outgoing="_IG0-ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vCelVCtpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vCelVStpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vCelVitpEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_E6JmwCtrEe-GQdByl4qvpg" name="Planificacion estrategica  de I+D+i+e" outgoing="_OO03ICtrEe-GQdByl4qvpg" incoming="_IG0-ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_E6K04StrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_E6K04CtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_E6K04itrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_E6K05StrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_E6K05itrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_E6K05ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_E6K06StrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_E6K06CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_E6K04ytrEe-GQdByl4qvpg" name="PlanificacionEstrategicasDeI+D+i+e" content="PlanificacionEstrategicasDeI+D+i+e" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_E6K05CtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_JJt-gCtrEe-GQdByl4qvpg" name="Gestion de fondos para la investigacion" outgoing="_Oo5kACtrEe-GQdByl4qvpg" incoming="_OO03ICtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JJulkStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JJulkCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JJulkitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JJullStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JJullitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JJullytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JJulmStrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JJulmCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_JJulkytrEe-GQdByl4qvpg" name="GestionDeFondosParaLaInvestigacion" content="GestionDeFondosParaLaInvestigacion" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_JJullCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_N2nygCtrEe-GQdByl4qvpg" name="Fin1" incoming="_Oo5kACtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_N2pAoCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_N2oZkCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_N2pAoStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_vCelZCtpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_2soKkC37Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_vCelZitpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_vCelZytpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IG0-ICtrEe-GQdByl4qvpg" target="_E6JmwCtrEe-GQdByl4qvpg" source="_vCelUytpEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IG1lMCtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IG1lMStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OO03ICtrEe-GQdByl4qvpg" target="_JJt-gCtrEe-GQdByl4qvpg" source="_E6JmwCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OO1eMCtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OO1eMStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Oo5kACtrEe-GQdByl4qvpg" target="_N2nygCtrEe-GQdByl4qvpg" source="_JJt-gCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Oo6LECtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Oo6LEStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_9Hv8QC3tEe-AtcusV1AfBQ" name="Director del Vicerrectorado de Investigacion" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_vCelbCtpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelbStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCelbitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCelbytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelcCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCelcStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCelcitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelcytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeldCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeldStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCelditpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeldytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeleCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_vCeleStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_vCeleitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_vCeleytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_0Iom0CtpEe-GQdByl4qvpg" name="PlanificacionEstrategicasDeI+D+i+e">
      <elements xmi:type="process:Lane" xmi:id="_vqvs8CtuEe-GQdByl4qvpg" name="Analista de Informacion" actor="_5cZ90C3rEe-AtcusV1AfBQ">
        <elements xmi:type="process:ServiceTask" xmi:id="_x44f0CtrEe-GQdByl4qvpg" name="Recibir informacion" outgoing="_jg2DcC4BEe-IB970bJnsFw" incoming="_x5BpyStrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x44f0StrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x44f0itrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x44f0ytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x44f1CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x44f1StrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x44f1itrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x44f1ytrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x44f2CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_x48xQytrEe-GQdByl4qvpg" name="Inicio del proceso" outgoing="_x5BpyStrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x48xRCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x48xRStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x48xRitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_m4sJAC4BEe-IB970bJnsFw" name="Analizar Informacion" outgoing="_pIFYwS4BEe-IB970bJnsFw" incoming="_jg2DcC4BEe-IB970bJnsFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jgyZES4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jgyZEC4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jgyZEi4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_F7SeYy4CEe-IB970bJnsFw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_F7SeZC4CEe-IB970bJnsFw" name="analizar_informacion" content="analizar_informacion" type="TYPE_VARIABLE" returnType="com.dexo.plan_estrategico.AnalizarInformacion">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_F7SeZS4CEe-IB970bJnsFw" name="analizar_informacion" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.AnalizarInformacion"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_F7SeZi4CEe-IB970bJnsFw" name="analizar_informacionInput.resultado_analisis" content="analizar_informacionInput?.resultado_analisis" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_F7SeZy4CEe-IB970bJnsFw" name="analizar_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_F7SeaC4CEe-IB970bJnsFw" type="JAVA_METHOD" expression="setResultado_analisis">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_F7SeaS4CEe-IB970bJnsFw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_F7Seai4CEe-IB970bJnsFw" name="analizar_informacion" content="analizar_informacion" type="TYPE_VARIABLE" returnType="com.dexo.plan_estrategico.AnalizarInformacion">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_F7Seay4CEe-IB970bJnsFw" name="analizar_informacion" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.AnalizarInformacion"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_F7SebC4CEe-IB970bJnsFw" name="analizar_informacionInput.fecha" content="analizar_informacionInput?.fecha" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_F7SebS4CEe-IB970bJnsFw" name="analizar_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_F7Sebi4CEe-IB970bJnsFw" type="JAVA_METHOD" expression="setFecha">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jgyZEy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jgyZFC4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jgyZFS4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jgyZFy4BEe-IB970bJnsFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jgyZFi4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_m4swGS4BEe-IB970bJnsFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_JJmNcC4CEe-IB970bJnsFw" name="AnalizarInformacion" content="aded2489-a983-4bc1-a2c8-c14c8be4dda8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_m4swGC4BEe-IB970bJnsFw">
            <inputs xmi:type="process:ContractInput" xmi:id="_F7SeYC4CEe-IB970bJnsFw" name="analizar_informacionInput" type="COMPLEX" dataReference="analizar_informacion" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_F7SeYS4CEe-IB970bJnsFw" name="resultado_analisis" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_F7SeYi4CEe-IB970bJnsFw" name="fecha" type="LOCALDATE" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_m4swGy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_agYDIC3uEe-AtcusV1AfBQ" name="Responsable de Planificación de I+D+I+E" actor="_7oA5wC3rEe-AtcusV1AfBQ">
        <elements xmi:type="process:Task" xmi:id="_x434wStrEe-GQdByl4qvpg" name="Modificar objetivos estrategicos" outgoing="_614QMC4BEe-IB970bJnsFw" incoming="_x4_NhitrEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x434witrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x434wytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x434xCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x434xStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x434xitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x434xytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x434yCtrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x434yStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x434yitrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXZzwC3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x434zCtrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x434zStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_x45t8CtrEe-GQdByl4qvpg" name="Gateway" outgoing="_x4-meCtrEe-GQdByl4qvpg _x4_NhitrEe-GQdByl4qvpg" incoming="_51RHwC4BEe-IB970bJnsFw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x45t8StrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x45t8itrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x45t8ytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SM29sC4CEe-IB970bJnsFw" name="Definir Objetivos Estrategicos" outgoing="_3QHqcC4BEe-IB970bJnsFw" incoming="_pIFYwS4BEe-IB970bJnsFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pIExsS4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pIExsC4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pIExsi4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_UXxWEy4CEe-IB970bJnsFw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UXxWFC4CEe-IB970bJnsFw" name="definir_objetivos_estrategicos" content="definir_objetivos_estrategicos" type="TYPE_VARIABLE" returnType="com.dexo.plan_estrategico.ObjetivosEstrategicos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UXxWFS4CEe-IB970bJnsFw" name="definir_objetivos_estrategicos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.ObjetivosEstrategicos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UXxWFi4CEe-IB970bJnsFw" name="definir_objetivos_estrategicosInput.objetivos_estrategicos" content="definir_objetivos_estrategicosInput?.objetivos_estrategicos" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UXxWFy4CEe-IB970bJnsFw" name="definir_objetivos_estrategicosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UXxWGC4CEe-IB970bJnsFw" type="JAVA_METHOD" expression="setObjetivos_estrategicos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UXxWGS4CEe-IB970bJnsFw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UXxWGi4CEe-IB970bJnsFw" name="definir_objetivos_estrategicos" content="definir_objetivos_estrategicos" type="TYPE_VARIABLE" returnType="com.dexo.plan_estrategico.ObjetivosEstrategicos">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UXxWGy4CEe-IB970bJnsFw" name="definir_objetivos_estrategicos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.ObjetivosEstrategicos"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UXxWHC4CEe-IB970bJnsFw" name="definir_objetivos_estrategicosInput.fecha" content="definir_objetivos_estrategicosInput?.fecha" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UXxWHS4CEe-IB970bJnsFw" name="definir_objetivos_estrategicosInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UXxWHi4CEe-IB970bJnsFw" type="JAVA_METHOD" expression="setFecha">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pIExsy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pIExtC4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pIExtS4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pIExty4BEe-IB970bJnsFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pIExti4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SM3kyS4CEe-IB970bJnsFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_U_5tEC4CEe-IB970bJnsFw" name="DefinirObjetivosEstrategicos" content="f24fea4d-cd93-4214-adec-647406945008" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SM3kyC4CEe-IB970bJnsFw">
            <inputs xmi:type="process:ContractInput" xmi:id="_UXxWEC4CEe-IB970bJnsFw" name="definir_objetivos_estrategicosInput" type="COMPLEX" dataReference="definir_objetivos_estrategicos" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_UXxWES4CEe-IB970bJnsFw" name="objetivos_estrategicos" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UXxWEi4CEe-IB970bJnsFw" name="fecha" type="LOCALDATE" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SM3kyy4CEe-IB970bJnsFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Soi0IC4CEe-IB970bJnsFw" name="Elaborar Plan de Accion" outgoing="_51RHwC4BEe-IB970bJnsFw" incoming="_3QHqcC4BEe-IB970bJnsFw _614QMC4BEe-IB970bJnsFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3QF1QS4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3QF1QC4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3QF1Qi4BEe-IB970bJnsFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3QF1Qy4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3QF1RC4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3QF1RS4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3QF1Ry4BEe-IB970bJnsFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3QF1Ri4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SojbOS4CEe-IB970bJnsFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_SojbOi4CEe-IB970bJnsFw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SojbOC4CEe-IB970bJnsFw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SojbOy4CEe-IB970bJnsFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_fj8DoC3uEe-AtcusV1AfBQ" name="Director del Vicerrectorado" actor="_45dloC3nEe-pm-hOycnQdg">
        <elements xmi:type="process:Task" xmi:id="_x45G4ytrEe-GQdByl4qvpg" name="Aprobar Estrategia de I+D+i+e " outgoing="_x4-mcCtrEe-GQdByl4qvpg" incoming="_x4-meCtrEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x45G5CtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x45G5StrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x45G5itrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_x45G5ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_x45G6CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_x45G6StrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_x45G6itrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_x45G6ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_x45G7CtrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXZzwS3_Ee-AtcusV1AfBQ" name="taskAutogeneratedForm" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_x45G7itrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_x45G7ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_x47jMCtrEe-GQdByl4qvpg" name="Fin del proceso" incoming="_x4-mcCtrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_x47jMStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_x47jMitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_x47jMytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_EyecMC4CEe-IB970bJnsFw" name="analizar_informacion" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.AnalizarInformacion">
        <defaultValue xmi:type="expression:Expression" xmi:id="_EyecMS4CEe-IB970bJnsFw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_P2LaMC4CEe-IB970bJnsFw" name="definir_objetivos_estrategicos" dataType="_vCelhCtpEe-GQdByl4qvpg" className="com.dexo.plan_estrategico.ObjetivosEstrategicos">
        <defaultValue xmi:type="expression:Expression" xmi:id="_P2LaMS4CEe-IB970bJnsFw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_0IqcDytpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_oVpzEC39Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_0IrDECtpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_0IrDEStpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x4-mcCtrEe-GQdByl4qvpg" target="_x47jMCtrEe-GQdByl4qvpg" source="_x45G4ytrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x4-mcStrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_x4-mcitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x4-meCtrEe-GQdByl4qvpg" name="si" target="_x45G4ytrEe-GQdByl4qvpg" source="_x45t8CtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x4-meStrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_x4-meitrEe-GQdByl4qvpg" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x4_NhitrEe-GQdByl4qvpg" name="no" target="_x434wStrEe-GQdByl4qvpg" source="_x45t8CtrEe-GQdByl4qvpg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x4_NhytrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_x4_NiCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_x5BpyStrEe-GQdByl4qvpg" target="_x44f0CtrEe-GQdByl4qvpg" source="_x48xQytrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_x5BpyitrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_x5BpyytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jg2DcC4BEe-IB970bJnsFw" target="_m4sJAC4BEe-IB970bJnsFw" source="_x44f0CtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jg2qgC4BEe-IB970bJnsFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jg2qgS4BEe-IB970bJnsFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pIFYwS4BEe-IB970bJnsFw" target="_SM29sC4CEe-IB970bJnsFw" source="_m4sJAC4BEe-IB970bJnsFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pIFYwi4BEe-IB970bJnsFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_pIFYwy4BEe-IB970bJnsFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3QHqcC4BEe-IB970bJnsFw" target="_Soi0IC4CEe-IB970bJnsFw" source="_SM29sC4CEe-IB970bJnsFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3QHqcS4BEe-IB970bJnsFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_3QHqci4BEe-IB970bJnsFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_51RHwC4BEe-IB970bJnsFw" name="¿Aprobacion del plan de accion?" target="_x45t8CtrEe-GQdByl4qvpg" source="_Soi0IC4CEe-IB970bJnsFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_51RHwS4BEe-IB970bJnsFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_51RHwi4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_614QMC4BEe-IB970bJnsFw" target="_Soi0IC4CEe-IB970bJnsFw" source="_x434wStrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_614QMS4BEe-IB970bJnsFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_614QMi4BEe-IB970bJnsFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_45dloC3nEe-pm-hOycnQdg" name="Director del Vicerrectorado de Investigacion"/>
      <actors xmi:type="process:Actor" xmi:id="_5cZ90C3rEe-AtcusV1AfBQ" name="Analista de Informacion" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_7oA5wC3rEe-AtcusV1AfBQ" name="Responsable de Planificación de I+D+I+E"/>
      <contract xmi:type="process:Contract" xmi:id="_0IrDEitpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcACtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcAStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcAitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcAytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcBCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcBStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcBitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcBytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcCCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcCStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcCitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcCytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0IqcDCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_0IqcDStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0IqcDitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_3Y3BcCtpEe-GQdByl4qvpg" name="GestionDeFondosParaLaInvestigacion">
      <elements xmi:type="process:Lane" xmi:id="_1VMuUCtuEe-GQdByl4qvpg" name="Responsable de Gestión de Fondos" actor="_apIPIC3xEe-AtcusV1AfBQ">
        <elements xmi:type="process:XORGateway" xmi:id="_4se6kCtrEe-GQdByl4qvpg" name="Compuerta2" outgoing="_4sqgwCtrEe-GQdByl4qvpg _4sqgyStrEe-GQdByl4qvpg" incoming="_4sru5itrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4se6kStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4se6kitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4se6kytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4snddCtrEe-GQdByl4qvpg" name="Definir Estrategia de Financiamiento" outgoing="_4sru5itrEe-GQdByl4qvpg" incoming="_4ssV_StrEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4soEgCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4soEgStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4soEgitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4soEgytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4soEhCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4soEhStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4soEhitrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4soEhytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4soEiCtrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXX-kC3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4soEiitrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4soEiytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_4sp5sCtrEe-GQdByl4qvpg" name="Inicio del proceso" outgoing="_4ss9BitrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4sp5sStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4sp5sitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4sp5sytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_4sp5uCtrEe-GQdByl4qvpg" name="Compuerta1" outgoing="_8WVrQCttEe-GQdByl4qvpg _97XIUCttEe-GQdByl4qvpg" incoming="_6f2qwCttEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4sp5uStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4sp5uitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4sp5uytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_gMGC4C25Ee-pm-hOycnQdg" name="Evaluar Fondos Disponibles" outgoing="_4ssV_StrEe-GQdByl4qvpg" incoming="_4ss9BitrEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4spSpCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4spSpStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4spSpitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4spSpytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4spSqCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4spSqStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4spSqitrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4spSqytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_gMGp-S25Ee-pm-hOycnQdg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXX-kS3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_gMGp-C25Ee-pm-hOycnQdg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_gMGp-y25Ee-pm-hOycnQdg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_T6xysC3vEe-AtcusV1AfBQ" name="Coordinador de Proyectos" actor="_jf7QsC3xEe-AtcusV1AfBQ">
        <elements xmi:type="process:Task" xmi:id="_4smPUCtrEe-GQdByl4qvpg" name="Asignar Fondos a Proyectos" outgoing="_4srH3ytrEe-GQdByl4qvpg" incoming="_4sqgyStrEe-GQdByl4qvpg _8WVrQCttEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4smPUStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4smPUitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4smPUytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4smPVCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4smPVStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4smPVitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4smPVytrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4smPWCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4smPWStrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXX-ki3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4smPWytrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4smPXCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_UX3XUC3vEe-AtcusV1AfBQ" name="Gestor de Relaciones Externas" actor="_idoGMC3xEe-AtcusV1AfBQ">
        <elements xmi:type="process:Task" xmi:id="_4sfhoCtrEe-GQdByl4qvpg" name="Negociar Condiciones de Financiamiento" outgoing="__EMYoCttEe-GQdByl4qvpg" incoming="_97XIUCttEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4sfhoStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4sfhoitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4sfhoytrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4sfhpCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4sfhpStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4sfhpitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4sfhpytrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4sfhqCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4sfhqStrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXX-ky3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4sfhqytrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4sfhrCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4soEjytrEe-GQdByl4qvpg" name="Solicitar Fondos Externos" outgoing="_6f2qwCttEe-GQdByl4qvpg" incoming="_4sqgwCtrEe-GQdByl4qvpg __EMYoCttEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4soEkCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4soEkStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4soEkitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4soEkytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4soElCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4soElStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4soElitrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4soElytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_0d4RgC3vEe-AtcusV1AfBQ" name="Director Vicerrectorado" actor="_hatQoC3xEe-AtcusV1AfBQ">
        <elements xmi:type="process:Task" xmi:id="_4sorkytrEe-GQdByl4qvpg" name="Aprobar Asignación de Fondos" outgoing="_4ssV9StrEe-GQdByl4qvpg" incoming="_4srH3ytrEe-GQdByl4qvpg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4sorlCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4sorlStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4sorlitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4sorlytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4sormCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4sormStrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4sormitrEe-GQdByl4qvpg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4sormytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4sornCtrEe-GQdByl4qvpg">
            <targetForm xmi:type="expression:Expression" xmi:id="_fXX-lC3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4sornitrEe-GQdByl4qvpg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4sornytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_4sm2YytrEe-GQdByl4qvpg" name="Cópia de Fin del proceso" incoming="_4ssV9StrEe-GQdByl4qvpg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4sm2ZCtrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4sm2ZStrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4sm2ZitrEe-GQdByl4qvpg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_3Y4PlStpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_fXX-lS3_Ee-AtcusV1AfBQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_3Y4PlytpEe-GQdByl4qvpg">
        <targetForm xmi:type="expression:Expression" xmi:id="_3Y4PmCtpEe-GQdByl4qvpg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4sqgwCtrEe-GQdByl4qvpg" name="no" target="_4soEjytrEe-GQdByl4qvpg" source="_4se6kCtrEe-GQdByl4qvpg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4sqgwStrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4sqgwitrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4sqgyStrEe-GQdByl4qvpg" name="si" target="_4smPUCtrEe-GQdByl4qvpg" source="_4se6kCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4sqgyitrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4sqgyytrEe-GQdByl4qvpg" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4srH3ytrEe-GQdByl4qvpg" target="_4sorkytrEe-GQdByl4qvpg" source="_4smPUCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4srH4CtrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4srH4StrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4sru5itrEe-GQdByl4qvpg" name="¿Fondos suficientes?" target="_4se6kCtrEe-GQdByl4qvpg" source="_4snddCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4sru5ytrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4sru6CtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4ssV9StrEe-GQdByl4qvpg" target="_4sm2YytrEe-GQdByl4qvpg" source="_4sorkytrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4ssV9itrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4ssV9ytrEe-GQdByl4qvpg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4ssV_StrEe-GQdByl4qvpg" target="_4snddCtrEe-GQdByl4qvpg" source="_gMGC4C25Ee-pm-hOycnQdg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4ssV_itrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4ssV_ytrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4ss9BitrEe-GQdByl4qvpg" target="_gMGC4C25Ee-pm-hOycnQdg" source="_4sp5sCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4ss9BytrEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_4ss9CCtrEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6f2qwCttEe-GQdByl4qvpg" name="¿Fondos aprobados?" target="_4sp5uCtrEe-GQdByl4qvpg" source="_4soEjytrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6f3R0CttEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_6f3R0SttEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8WVrQCttEe-GQdByl4qvpg" name="si" target="_4smPUCtrEe-GQdByl4qvpg" source="_4sp5uCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8WWSUCttEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8WWSUSttEe-GQdByl4qvpg" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_97XIUCttEe-GQdByl4qvpg" name="no" target="_4sfhoCtrEe-GQdByl4qvpg" source="_4sp5uCtrEe-GQdByl4qvpg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_97XIUSttEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="_97XIUittEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__EMYoCttEe-GQdByl4qvpg" target="_4soEjytrEe-GQdByl4qvpg" source="_4sfhoCtrEe-GQdByl4qvpg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__EMYoSttEe-GQdByl4qvpg"/>
        <condition xmi:type="expression:Expression" xmi:id="__EMYoittEe-GQdByl4qvpg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_apIPIC3xEe-AtcusV1AfBQ" name="Responsable de Gestión de Fondos" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_hatQoC3xEe-AtcusV1AfBQ" name="Director Vicerrectorado"/>
      <actors xmi:type="process:Actor" xmi:id="_idoGMC3xEe-AtcusV1AfBQ" name="Gestor de Relaciones Externas"/>
      <actors xmi:type="process:Actor" xmi:id="_jf7QsC3xEe-AtcusV1AfBQ" name="Coordinador de Proyectos"/>
      <contract xmi:type="process:Contract" xmi:id="_3Y4PmStpEe-GQdByl4qvpg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ogCtpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ogStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3ogitpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ogytpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ohCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3ohStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3ohitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y3ohytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y3oiCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y3oiStpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y4PkCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y4PkStpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_3Y4PkitpEe-GQdByl4qvpg">
        <name xmi:type="expression:Expression" xmi:id="_3Y4PkytpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_3Y4PlCtpEe-GQdByl4qvpg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_vCelfCtpEe-GQdByl4qvpg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_vCelfStpEe-GQdByl4qvpg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_vCelfitpEe-GQdByl4qvpg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_vCelfytpEe-GQdByl4qvpg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_vCelgCtpEe-GQdByl4qvpg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_vCelgStpEe-GQdByl4qvpg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_vCelgitpEe-GQdByl4qvpg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_vCelgytpEe-GQdByl4qvpg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_vCelhCtpEe-GQdByl4qvpg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_vCelhStpEe-GQdByl4qvpg" type="Process" element="_vCelUCtpEe-GQdByl4qvpg" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_vCelhitpEe-GQdByl4qvpg" type="2007" element="_vCelUStpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_vCelhytpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_vCeliCtpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_vCeliStpEe-GQdByl4qvpg" type="3007" element="_vCelUitpEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_vCeliitpEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vCeliytpEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_vCeljytpEe-GQdByl4qvpg" type="3002" element="_vCelUytpEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_vCelkCtpEe-GQdByl4qvpg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vCelkStpEe-GQdByl4qvpg" x="3" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCelkitpEe-GQdByl4qvpg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E6PGUCtrEe-GQdByl4qvpg" type="3063" element="_E6JmwCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E6PtYCtrEe-GQdByl4qvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E6PGUStrEe-GQdByl4qvpg" x="232" y="97" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JJvzsCtrEe-GQdByl4qvpg" type="3063" element="_JJt-gCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JJwawCtrEe-GQdByl4qvpg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JJvzsStrEe-GQdByl4qvpg" x="498" y="103" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N2rc4CtrEe-GQdByl4qvpg" type="3003" element="_N2nygCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_N2sD8CtrEe-GQdByl4qvpg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_N2sD8StrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N2rc4StrEe-GQdByl4qvpg" x="850" y="154"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vCelkytpEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vCellCtpEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vCellStpEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vCellitpEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCellytpEe-GQdByl4qvpg" x="48" y="10" width="1227" height="267"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_vCelmCtpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_vCelmStpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_vCelmitpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_vCelmytpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vCelnCtpEe-GQdByl4qvpg" width="1250" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_0IsRMCtpEe-GQdByl4qvpg" type="2007" element="_0Iom0CtpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Is4QCtpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0Is4QStpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_vqxiICtuEe-GQdByl4qvpg" type="3007" element="_vqvs8CtuEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_vqyJMCtuEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vqyJMStuEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_x45G4CtrEe-GQdByl4qvpg" type="3027" element="_x44f0CtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x45G4StrEe-GQdByl4qvpg" type="5017" element="_x44f0CtrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x45G4itrEe-GQdByl4qvpg" x="148" y="55" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x48xRytrEe-GQdByl4qvpg" type="3002" element="_x48xQytrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_x48xSCtrEe-GQdByl4qvpg" type="5024" element="_x48xQytrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_x48xSStrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x48xSitrEe-GQdByl4qvpg" x="60" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m4tXIC4BEe-IB970bJnsFw" type="3005" element="_m4sJAC4BEe-IB970bJnsFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_m4tXIi4BEe-IB970bJnsFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m4tXIS4BEe-IB970bJnsFw" x="368" y="56" width="132" height="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vqxiIStuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vqxiIituEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vqxiIytuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vqyJMituEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vqxiJCtuEe-GQdByl4qvpg" x="48" y="10" width="1213" height="235"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_agYqMC3uEe-AtcusV1AfBQ" type="3007" element="_agYDIC3uEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_agZRQC3uEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_agZRQS3uEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_x434zitrEe-GQdByl4qvpg" type="3005" element="_x434wStrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x434zytrEe-GQdByl4qvpg" type="5005" element="_x434wStrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x4340CtrEe-GQdByl4qvpg" x="690" y="13" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x45t9CtrEe-GQdByl4qvpg" type="3008" element="_x45t8CtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_x45t9StrEe-GQdByl4qvpg" visible="false" type="5026" element="_x45t8CtrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_x45t9itrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x45t9ytrEe-GQdByl4qvpg" x="808" y="111" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SM4L0C4CEe-IB970bJnsFw" type="3005" element="_SM29sC4CEe-IB970bJnsFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SM4L0i4CEe-IB970bJnsFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SM4L0S4CEe-IB970bJnsFw" x="258" y="82" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SojbPC4CEe-IB970bJnsFw" type="3005" element="_Soi0IC4CEe-IB970bJnsFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SokCQC4CEe-IB970bJnsFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SojbPS4CEe-IB970bJnsFw" x="460" y="132" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_agYqMS3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_agYqMi3uEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_agYqMy3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_agZRQi3uEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_agYqNC3uEe-AtcusV1AfBQ" x="23" y="235" width="1213" height="277"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_fj940C3uEe-AtcusV1AfBQ" type="3007" element="_fj8DoC3uEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_fj941S3uEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fj941i3uEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_x45G8CtrEe-GQdByl4qvpg" type="3005" element="_x45G4ytrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_x45G8StrEe-GQdByl4qvpg" type="5005" element="_x45G4ytrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x45G8itrEe-GQdByl4qvpg" x="859" y="97" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_x47jNCtrEe-GQdByl4qvpg" type="3003" element="_x47jMCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_x47jNStrEe-GQdByl4qvpg" type="5025" element="_x47jMCtrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_x47jNitrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x47jNytrEe-GQdByl4qvpg" x="1087" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fj940S3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fj940i3uEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fj940y3uEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fj941y3uEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fj941C3uEe-AtcusV1AfBQ" x="48" y="460" width="1213" height="193"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0IsRMStpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0IsRMitpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0IsRMytpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0Is4QitpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0IsRNCtpEe-GQdByl4qvpg" width="1236" height="474"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_3Y7S4CtpEe-GQdByl4qvpg" type="2007" element="_3Y3BcCtpEe-GQdByl4qvpg">
      <children xmi:type="notation:DecorationNode" xmi:id="_3Y758CtpEe-GQdByl4qvpg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_3Y758StpEe-GQdByl4qvpg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_1VN8cCtuEe-GQdByl4qvpg" type="3007" element="_1VMuUCtuEe-GQdByl4qvpg">
          <children xmi:type="notation:DecorationNode" xmi:id="_1VOjgCtuEe-GQdByl4qvpg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_1VOjgStuEe-GQdByl4qvpg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_4se6lCtrEe-GQdByl4qvpg" type="3008" element="_4se6kCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_4se6lStrEe-GQdByl4qvpg" visible="false" type="5026" element="_4se6kCtrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4se6litrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4se6lytrEe-GQdByl4qvpg" x="707" y="70" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4soEjCtrEe-GQdByl4qvpg" type="3005" element="_4snddCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4soEjStrEe-GQdByl4qvpg" type="5005" element="_4snddCtrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4soEjitrEe-GQdByl4qvpg" x="422" y="55" width="149" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4sp5tCtrEe-GQdByl4qvpg" type="3002" element="_4sp5sCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sp5tStrEe-GQdByl4qvpg" type="5024" element="_4sp5sCtrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4sp5titrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sp5tytrEe-GQdByl4qvpg" x="80" y="183"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4sp5vCtrEe-GQdByl4qvpg" type="3008" element="_4sp5uCtrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sp5vStrEe-GQdByl4qvpg" visible="false" type="5026" element="_4sp5uCtrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4sp5vitrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sp5vytrEe-GQdByl4qvpg" x="430" y="207" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gMHRAC25Ee-pm-hOycnQdg" type="3005" element="_gMGC4C25Ee-pm-hOycnQdg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gMH4EC25Ee-pm-hOycnQdg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gMHRAS25Ee-pm-hOycnQdg" x="156" y="62" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_1VN8cStuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_1VN8cituEe-GQdByl4qvpg" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_1VN8cytuEe-GQdByl4qvpg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_1VOjgituEe-GQdByl4qvpg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1VN8dCtuEe-GQdByl4qvpg" x="48" y="10" width="1175" height="324"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_T6zA0C3vEe-AtcusV1AfBQ" type="3007" element="_T6xysC3vEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_T6zA1S3vEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_T6zA1i3vEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_4sm2YCtrEe-GQdByl4qvpg" type="3005" element="_4smPUCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sm2YStrEe-GQdByl4qvpg" type="5005" element="_4smPUCtrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sm2YitrEe-GQdByl4qvpg" x="740" y="75" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_T6zA0S3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_T6zA0i3vEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_T6zA0y3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_T6zA1y3vEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_T6zA1C3vEe-AtcusV1AfBQ" x="48" y="474" width="1175" height="190"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_UX5MgC3vEe-AtcusV1AfBQ" type="3007" element="_UX3XUC3vEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_UX5MhS3vEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_UX5zkC3vEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_4sfhrStrEe-GQdByl4qvpg" type="3005" element="_4sfhoCtrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sfhritrEe-GQdByl4qvpg" type="5005" element="_4sfhoCtrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sfhrytrEe-GQdByl4qvpg" x="341" y="56" width="167" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4sorkCtrEe-GQdByl4qvpg" type="3027" element="_4soEjytrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sorkStrEe-GQdByl4qvpg" type="5017" element="_4soEjytrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sorkitrEe-GQdByl4qvpg" x="113" y="56" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_UX5MgS3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_UX5Mgi3vEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_UX5Mgy3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_UX5zkS3vEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UX5MhC3vEe-AtcusV1AfBQ" x="48" y="664" width="1175" height="199"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_0d5foC3vEe-AtcusV1AfBQ" type="3007" element="_0d4RgC3vEe-AtcusV1AfBQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_0d5fpS3vEe-AtcusV1AfBQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0d5fpi3vEe-AtcusV1AfBQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_4spSoCtrEe-GQdByl4qvpg" type="3005" element="_4sorkytrEe-GQdByl4qvpg" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4spSoStrEe-GQdByl4qvpg" type="5005" element="_4sorkytrEe-GQdByl4qvpg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4spSoitrEe-GQdByl4qvpg" x="783" y="10" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4sndcCtrEe-GQdByl4qvpg" type="3003" element="_4sm2YytrEe-GQdByl4qvpg" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_4sndcStrEe-GQdByl4qvpg" type="5025" element="_4sm2YytrEe-GQdByl4qvpg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4sndcitrEe-GQdByl4qvpg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4sndcytrEe-GQdByl4qvpg" x="1011" y="40"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0d5foS3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0d5foi3vEe-AtcusV1AfBQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0d5foy3vEe-AtcusV1AfBQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0d5fpy3vEe-AtcusV1AfBQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0d5fpC3vEe-AtcusV1AfBQ" x="48" y="840" width="1175" height="138"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_3Y7S4StpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_3Y7S4itpEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_3Y7S4ytpEe-GQdByl4qvpg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_3Y758itpEe-GQdByl4qvpg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3Y7S5CtpEe-GQdByl4qvpg" width="1198" height="477"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_vCelnStpEe-GQdByl4qvpg"/>
    <edges xmi:type="notation:Connector" xmi:id="_IG4BcCtrEe-GQdByl4qvpg" type="4001" element="_IG0-ICtrEe-GQdByl4qvpg" source="_vCeljytpEe-GQdByl4qvpg" target="_E6PGUCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IG4ogCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IG4ogStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IG4BcStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IG4BcitrEe-GQdByl4qvpg" points="[-8, -3, -226, -65]$[212, 100, -6, 38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IG9hACtrEe-GQdByl4qvpg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OO2sUCtrEe-GQdByl4qvpg" type="4001" element="_OO03ICtrEe-GQdByl4qvpg" source="_E6PGUCtrEe-GQdByl4qvpg" target="_JJvzsCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OO3TYCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OO3TYStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OO2sUStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OO2sUitrEe-GQdByl4qvpg" points="[0, 9, -256, 0]$[294, 18, 38, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OO69wCtrEe-GQdByl4qvpg" id="(1.0,0.39473684210526316)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OO7k0CtrEe-GQdByl4qvpg" id="(0.7888888888888889,0.6444444444444445)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Oo7ZMCtrEe-GQdByl4qvpg" type="4001" element="_Oo5kACtrEe-GQdByl4qvpg" source="_JJvzsCtrEe-GQdByl4qvpg" target="_N2rc4CtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Oo8AQCtrEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Oo8AQStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Oo7ZMStrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Oo7ZMitrEe-GQdByl4qvpg" points="[0, 0, -187, -35]$[185, 20, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Oo_qoCtrEe-GQdByl4qvpg" id="(1.0,0.34444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x4-mcytrEe-GQdByl4qvpg" type="4001" element="_x4-mcCtrEe-GQdByl4qvpg" source="_x45G8CtrEe-GQdByl4qvpg" target="_x47jNCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x4-mdCtrEe-GQdByl4qvpg" type="6001" element="_x4-mcCtrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x4-mdStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x4-mditrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x4-mdytrEe-GQdByl4qvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x4_NgCtrEe-GQdByl4qvpg" type="4001" element="_x4-meCtrEe-GQdByl4qvpg" source="_x45t9CtrEe-GQdByl4qvpg" target="_x45G8CtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x4_NgStrEe-GQdByl4qvpg" type="6001" element="_x4-meCtrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x4_NgitrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x4_NgytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x4_NhCtrEe-GQdByl4qvpg" points="[-7, -2, -110, -20]$[43, 18, -60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x4_NhStrEe-GQdByl4qvpg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x4_NiStrEe-GQdByl4qvpg" type="4001" element="_x4_NhitrEe-GQdByl4qvpg" source="_x45t9CtrEe-GQdByl4qvpg" target="_x434zitrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x4_NiitrEe-GQdByl4qvpg" type="6001" element="_x4_NhitrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x4_NiytrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x4_NjCtrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x4_NjStrEe-GQdByl4qvpg" points="[-22, 15, -158, -130]$[-22, 67, -158, -78]$[90, 67, -46, -78]$[90, 115, -46, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x4_NjitrEe-GQdByl4qvpg" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_x5BpzCtrEe-GQdByl4qvpg" type="4001" element="_x5BpyStrEe-GQdByl4qvpg" source="_x48xRytrEe-GQdByl4qvpg" target="_x45G4CtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_x5BpzStrEe-GQdByl4qvpg" type="6001" element="_x5BpyStrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_x5BpzitrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_x5BpzytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x5Bp0CtrEe-GQdByl4qvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4sqgwytrEe-GQdByl4qvpg" type="4001" element="_4sqgwCtrEe-GQdByl4qvpg" source="_4se6lCtrEe-GQdByl4qvpg" target="_4sorkCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4sqgxCtrEe-GQdByl4qvpg" type="6001" element="_4sqgwCtrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4sqgxStrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4sqgxitrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4sqgxytrEe-GQdByl4qvpg" points="[-22, 12, 555, -557]$[-22, 140, 555, -429]$[-575, 140, 2, -429]$[-575, 539, 2, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4sqgyCtrEe-GQdByl4qvpg" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4srH0CtrEe-GQdByl4qvpg" type="4001" element="_4sqgyStrEe-GQdByl4qvpg" source="_4se6lCtrEe-GQdByl4qvpg" target="_4sm2YCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4srH0StrEe-GQdByl4qvpg" type="6001" element="_4sqgyStrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4srH0itrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4srH0ytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4srH1CtrEe-GQdByl4qvpg" points="[-6, -3, -327, -166]$[261, 167, -60, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4srH1StrEe-GQdByl4qvpg" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4sru4CtrEe-GQdByl4qvpg" type="4001" element="_4srH3ytrEe-GQdByl4qvpg" source="_4sm2YCtrEe-GQdByl4qvpg" target="_4spSoCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4sru4StrEe-GQdByl4qvpg" type="6001" element="_4srH3ytrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4sru4itrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4sru4ytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4sru5CtrEe-GQdByl4qvpg" points="[0, 0, -126, 98]$[117, -63, -9, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4sru5StrEe-GQdByl4qvpg" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4sru6StrEe-GQdByl4qvpg" type="4001" element="_4sru5itrEe-GQdByl4qvpg" source="_4soEjCtrEe-GQdByl4qvpg" target="_4se6lCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4sru6itrEe-GQdByl4qvpg" type="6001" element="_4sru5itrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4sru6ytrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4sru7CtrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4sru7StrEe-GQdByl4qvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4ssV-CtrEe-GQdByl4qvpg" type="4001" element="_4ssV9StrEe-GQdByl4qvpg" source="_4spSoCtrEe-GQdByl4qvpg" target="_4sndcCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4ssV-StrEe-GQdByl4qvpg" type="6001" element="_4ssV9StrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4ssV-itrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4ssV-ytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4ssV_CtrEe-GQdByl4qvpg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4ss9ACtrEe-GQdByl4qvpg" type="4001" element="_4ssV_StrEe-GQdByl4qvpg" source="_gMHRAC25Ee-pm-hOycnQdg" target="_4soEjCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4ss9AStrEe-GQdByl4qvpg" type="6001" element="_4ssV_StrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4ss9AitrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4ss9AytrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4ss9BCtrEe-GQdByl4qvpg" points="[0, 0, -43, -106]$[118, 110, 75, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4ss9BStrEe-GQdByl4qvpg" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4ss9CStrEe-GQdByl4qvpg" type="4001" element="_4ss9BitrEe-GQdByl4qvpg" source="_4sp5tCtrEe-GQdByl4qvpg" target="_gMHRAC25Ee-pm-hOycnQdg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4ss9CitrEe-GQdByl4qvpg" type="6001" element="_4ss9BitrEe-GQdByl4qvpg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4ss9CytrEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4ss9DCtrEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4ss9DStrEe-GQdByl4qvpg" points="[-3, -24, -128, 80]$[122, -134, -3, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4ss9DitrEe-GQdByl4qvpg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6f3R0ittEe-GQdByl4qvpg" type="4001" element="_6f2qwCttEe-GQdByl4qvpg" source="_4sorkCtrEe-GQdByl4qvpg" target="_4sp5vCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6f344CttEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6f344SttEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6f3R0yttEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6f3R1CttEe-GQdByl4qvpg" points="[-20, -30, -238, 341]$[-20, -125, -238, 246]$[151, -125, -67, 246]$[151, -371, -67, 0]$[197, -371, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6f5HACttEe-GQdByl4qvpg" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8WXgcCttEe-GQdByl4qvpg" type="4001" element="_8WVrQCttEe-GQdByl4qvpg" source="_4sp5vCtrEe-GQdByl4qvpg" target="_4sm2YCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8WYHgCttEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8WYHgSttEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8WXgcSttEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8WXgcittEe-GQdByl4qvpg" points="[-12, 6, -231, 117]$[159, -114, -60, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8WajwCttEe-GQdByl4qvpg" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_97mY4CttEe-GQdByl4qvpg" type="4001" element="_97XIUCttEe-GQdByl4qvpg" source="_4sp5vCtrEe-GQdByl4qvpg" target="_4sfhrStrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_97m_8CttEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_97m_8SttEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_97mY4SttEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_97mY4ittEe-GQdByl4qvpg" points="[-22, 12, -167, -365]$[-22, 362, -167, -15]$[19, 362, -126, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_97qDQCttEe-GQdByl4qvpg" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_97qDQSttEe-GQdByl4qvpg" id="(0.7544910179640718,0.6746987951807228)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__EM_sCttEe-GQdByl4qvpg" type="4001" element="__EMYoCttEe-GQdByl4qvpg" source="_4sfhrStrEe-GQdByl4qvpg" target="_4sorkCtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__EM_syttEe-GQdByl4qvpg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__EM_tCttEe-GQdByl4qvpg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__EM_sSttEe-GQdByl4qvpg" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__EM_sittEe-GQdByl4qvpg" points="[0, 0, -204, 87]$[195, -57, -9, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__EO04CttEe-GQdByl4qvpg" id="(1.0,0.3493975903614458)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jg3RkC4BEe-IB970bJnsFw" type="4001" element="_jg2DcC4BEe-IB970bJnsFw" source="_x45G4CtrEe-GQdByl4qvpg" target="_m4tXIC4BEe-IB970bJnsFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jg3Rky4BEe-IB970bJnsFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jg3RlC4BEe-IB970bJnsFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jg3RkS4BEe-IB970bJnsFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jg3Rki4BEe-IB970bJnsFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pIFYxC4BEe-IB970bJnsFw" type="4001" element="_pIFYwS4BEe-IB970bJnsFw" source="_m4tXIC4BEe-IB970bJnsFw" target="_SM4L0C4CEe-IB970bJnsFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pIF_0C4BEe-IB970bJnsFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pIF_0S4BEe-IB970bJnsFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pIFYxS4BEe-IB970bJnsFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pIFYxi4BEe-IB970bJnsFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3QIRgC4BEe-IB970bJnsFw" type="4001" element="_3QHqcC4BEe-IB970bJnsFw" source="_SM4L0C4CEe-IB970bJnsFw" target="_SojbPC4CEe-IB970bJnsFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3QIRgy4BEe-IB970bJnsFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3QIRhC4BEe-IB970bJnsFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3QIRgS4BEe-IB970bJnsFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3QIRgi4BEe-IB970bJnsFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_51SV4C4BEe-IB970bJnsFw" type="4001" element="_51RHwC4BEe-IB970bJnsFw" source="_SojbPC4CEe-IB970bJnsFw" target="_x45t9CtrEe-GQdByl4qvpg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_51SV4y4BEe-IB970bJnsFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_51SV5C4BEe-IB970bJnsFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_51SV4S4BEe-IB970bJnsFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_51SV4i4BEe-IB970bJnsFw" points="[-60, 25, -309, 60]$[-60, 41, -309, 76]$[115, 41, -134, 76]$[115, -32, -134, 3]$[230, -32, -19, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_51UyIC4BEe-IB970bJnsFw" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_615eUC4BEe-IB970bJnsFw" type="4001" element="_614QMC4BEe-IB970bJnsFw" source="_x434zitrEe-GQdByl4qvpg" target="_SojbPC4CEe-IB970bJnsFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_615eUy4BEe-IB970bJnsFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_615eVC4BEe-IB970bJnsFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_615eUS4BEe-IB970bJnsFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_615eUi4BEe-IB970bJnsFw" points="[-120, 12, 170, -106]$[-290, 12, 0, -106]$[-290, 88, 0, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_618hoC4BEe-IB970bJnsFw" id="(1.0,0.5166666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
