<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_xsiBQC5dEe-mJPIsZDPUkA" name="PM03.01_Gestion_Institucional" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_xsiBQS5dEe-mJPIsZDPUkA" name="PM03.01">
      <elements xmi:type="process:Lane" xmi:id="_xsiBQi5dEe-mJPIsZDPUkA" name="Vicerrectorado de Gestion Institucional" actor="_xsiBbi5dEe-mJPIsZDPUkA">
        <elements xmi:type="process:StartEvent" xmi:id="_xsiBQy5dEe-mJPIsZDPUkA" name="Inicio proceso" outgoing="_xsiBZS5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBRC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBRS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBRi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_xsiBRy5dEe-mJPIsZDPUkA" name="Ética y Buen Gobierno Institucional" outgoing="_xsiBaC5dEe-mJPIsZDPUkA" incoming="_xsiBZS5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBSC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBSS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBSi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiBSy5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiBTC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiBTS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiBTi5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiBTy5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_xsiBUC5dEe-mJPIsZDPUkA" name="PlanificacionEstrategicasDeI+D+i+e" content="PlanificacionEstrategicasDeI+D+i+e" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_xsiBUS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_xsiBUi5dEe-mJPIsZDPUkA" name="Desarrollo Personal y Profesional en el puesto de trabajo con equidad e inclusión Social" outgoing="_xsiBay5dEe-mJPIsZDPUkA" incoming="_xsiBaC5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBUy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBVC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBVS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiBVi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiBVy5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiBWC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiBWS5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiBWi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_xsiBWy5dEe-mJPIsZDPUkA" name="GestionDeFondosParaLaInvestigacion" content="GestionDeFondosParaLaInvestigacion" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_xsiBXC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_xsiBXS5dEe-mJPIsZDPUkA" name="Fin1" incoming="_xsiBay5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBXi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBXy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBYC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_xsiBYS5dEe-mJPIsZDPUkA">
        <targetForm xmi:type="expression:Expression" xmi:id="_EkUpgDI2Ee-CdauvfITryg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_xsiBYy5dEe-mJPIsZDPUkA">
        <targetForm xmi:type="expression:Expression" xmi:id="_xsiBZC5dEe-mJPIsZDPUkA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiBZS5dEe-mJPIsZDPUkA" target="_xsiBRy5dEe-mJPIsZDPUkA" source="_xsiBQy5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiBZi5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiBZy5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiBaC5dEe-mJPIsZDPUkA" target="_xsiBUi5dEe-mJPIsZDPUkA" source="_xsiBRy5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiBaS5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiBai5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiBay5dEe-mJPIsZDPUkA" target="_xsiBXS5dEe-mJPIsZDPUkA" source="_xsiBUi5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiBbC5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiBbS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_xsiBbi5dEe-mJPIsZDPUkA" name="Director del Vicerrectorado de Investigacion" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_xsiBby5dEe-mJPIsZDPUkA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiBcC5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiBcS5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiBci5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiBcy5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiBdC5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiBdS5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiBdi5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiBdy5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiBeC5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiBeS5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiBei5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiBey5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiBfC5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiBfS5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiBfi5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_xsiBfy5dEe-mJPIsZDPUkA" name="PM03.01.01">
      <elements xmi:type="process:Lane" xmi:id="_xsiBgC5dEe-mJPIsZDPUkA" name="Asistente de Gestión Institucional" actor="_XzrpgC9FEe-DGtHuJw_PQw">
        <elements xmi:type="process:ServiceTask" xmi:id="_xsiBgS5dEe-mJPIsZDPUkA" name="Recibir informacion" outgoing="_xsiCOi5dEe-mJPIsZDPUkA" incoming="_xsiCNy5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBgi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBgy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBhC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiBhS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiBhi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiBhy5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiBiC5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiBiS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_xsiBii5dEe-mJPIsZDPUkA" name="Inicio del proceso" outgoing="_xsiCNy5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBiy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBjC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBjS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xsiBji5dEe-mJPIsZDPUkA" name="Recibir diagnósticos y reportes anuales" outgoing="_xsiCPS5dEe-mJPIsZDPUkA" incoming="_xsiCOi5dEe-mJPIsZDPUkA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBjy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBkC5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBkS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_pctp0C9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pctp0S9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pctp0i9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pctp0y9SEe-DGtHuJw_PQw" name="recibir_informacionInput.diagnostico" content="recibir_informacionInput?.diagnostico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pctp1C9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pctp1S9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setDiagnostico">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pctp1i9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pctp1y9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pctp2C9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pctp2S9SEe-DGtHuJw_PQw" name="recibir_informacionInput.informe" content="recibir_informacionInput?.informe" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pctp2i9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pctp2y9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setInforme">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_pctp3C9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pctp3S9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pctp3i9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pctp3y9SEe-DGtHuJw_PQw" name="recibir_informacionInput.pei" content="recibir_informacionInput?.pei" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_pctp4C9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_pctp4S9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setPei">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiBni5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiBny5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiBoC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiBoS5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiBoi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xsiBoy5dEe-mJPIsZDPUkA">
            <targetForm xmi:type="expression:Expression" xmi:id="_xsiBpC5dEe-mJPIsZDPUkA" name="RecibirInformacionEtica" content="b51e7600-3397-46cf-b685-20d9d3ba3525" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xsiBpS5dEe-mJPIsZDPUkA">
            <inputs xmi:type="process:ContractInput" xmi:id="_pctCwC9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" dataReference="recibir_informacion" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_pctCwS9SEe-DGtHuJw_PQw" name="diagnostico" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pctCwi9SEe-DGtHuJw_PQw" name="informe" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_pctCwy9SEe-DGtHuJw_PQw" name="pei" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xsiBqS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_xsiBqi5dEe-mJPIsZDPUkA" name="Coordinadora Administrativa" actor="_pZwvYC9FEe-DGtHuJw_PQw">
        <elements xmi:type="process:Task" xmi:id="_xsiBvC5dEe-mJPIsZDPUkA" name="Elaborar el Plan Anual de Responsabilidad Social Universitaria" outgoing="_xsiCQC5dEe-mJPIsZDPUkA" incoming="_xsiCPS5dEe-mJPIsZDPUkA _xsiCNC5dEe-mJPIsZDPUkA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBvS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBvi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBvy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_47UF0i9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_47UF0y9SEe-DGtHuJw_PQw" name="elaborar_rsu" content="elaborar_rsu" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.RSUEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_47UF1C9SEe-DGtHuJw_PQw" name="elaborar_rsu" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.RSUEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_47UF1S9SEe-DGtHuJw_PQw" name="elaborar_rsuInput.rsu" content="elaborar_rsuInput?.rsu" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_47UF1i9SEe-DGtHuJw_PQw" name="elaborar_rsuInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_47UF1y9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setRsu">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8riPJC9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8riPJS9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8riPJi9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8riPJy9SEe-DGtHuJw_PQw" name="recibir_informacionInput.diagnostico" content="recibir_informacionInput?.diagnostico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8riPKC9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8riPKS9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setDiagnostico">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8riPKi9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8riPKy9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8riPLC9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8riPLS9SEe-DGtHuJw_PQw" name="recibir_informacionInput.informe" content="recibir_informacionInput?.informe" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8riPLi9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8riPLy9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setInforme">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8riPMC9SEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8riPMS9SEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8riPMi9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8riPMy9SEe-DGtHuJw_PQw" name="recibir_informacionInput.pei" content="recibir_informacionInput?.pei" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8riPNC9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8riPNS9SEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setPei">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiBzC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiBzS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiBzi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiBzy5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiB0C5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xsiB0S5dEe-mJPIsZDPUkA">
            <targetForm xmi:type="expression:Expression" xmi:id="_xsiB0i5dEe-mJPIsZDPUkA" name="ElaborarRsuEtica" content="bdc75b9e-fc37-405f-86eb-b4c6a02e7a18" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xsiB0y5dEe-mJPIsZDPUkA">
            <inputs xmi:type="process:ContractInput" xmi:id="_47UF0C9SEe-DGtHuJw_PQw" name="elaborar_rsuInput" type="COMPLEX" dataReference="elaborar_rsu" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_47UF0S9SEe-DGtHuJw_PQw" name="rsu" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_8riPIC9SEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" dataReference="recibir_informacion" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_8riPIS9SEe-DGtHuJw_PQw" name="diagnostico" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8riPIi9SEe-DGtHuJw_PQw" name="informe" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_8riPIy9SEe-DGtHuJw_PQw" name="pei" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xsiB1y5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_xsiCEi5dEe-mJPIsZDPUkA" name="Director de Gestión Institucional" actor="_xsiCSS5dEe-mJPIsZDPUkA">
        <elements xmi:type="process:EndEvent" xmi:id="_xsiCIC5dEe-mJPIsZDPUkA" name="Fin del proceso" incoming="_n2FucC9LEe-DGtHuJw_PQw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiCIS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiCIi5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiCIy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xsiB2C5dEe-mJPIsZDPUkA" name="Validar el Plan de RSU con las partes interesadas" outgoing="_xsiCQy5dEe-mJPIsZDPUkA" incoming="_xsiCQC5dEe-mJPIsZDPUkA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiB2S5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiB2i5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiB2y5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Agu_FC9TEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Agu_FS9TEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Agu_Fi9TEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Agu_Fy9TEe-DGtHuJw_PQw" name="recibir_informacionInput.diagnostico" content="recibir_informacionInput?.diagnostico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Agu_GC9TEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Agu_GS9TEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setDiagnostico">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Agu_Gi9TEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Agu_Gy9TEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Agu_HC9TEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Agu_HS9TEe-DGtHuJw_PQw" name="recibir_informacionInput.informe" content="recibir_informacionInput?.informe" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Agu_Hi9TEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Agu_Hy9TEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setInforme">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Agu_IC9TEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Agu_IS9TEe-DGtHuJw_PQw" name="recibir_informacion" content="recibir_informacion" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.EntradasEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Agu_Ii9TEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Agu_Iy9TEe-DGtHuJw_PQw" name="recibir_informacionInput.pei" content="recibir_informacionInput?.pei" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Agu_JC9TEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Agu_JS9TEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setPei">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_CFBcUi9TEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CFBcUy9TEe-DGtHuJw_PQw" name="elaborar_rsu" content="elaborar_rsu" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.RSUEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CFBcVC9TEe-DGtHuJw_PQw" name="elaborar_rsu" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.RSUEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CFBcVS9TEe-DGtHuJw_PQw" name="elaborar_rsuInput.rsu" content="elaborar_rsuInput?.rsu" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_CFBcVi9TEe-DGtHuJw_PQw" name="elaborar_rsuInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CFBcVy9TEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setRsu">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_DHHLci9TEe-DGtHuJw_PQw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DHHLcy9TEe-DGtHuJw_PQw" name="aprobar_rsu" content="aprobar_rsu" type="TYPE_VARIABLE" returnType="com.dex.gestion_etica.ValidacionEtica">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_DHHLdC9TEe-DGtHuJw_PQw" name="aprobar_rsu" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.ValidacionEtica"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DHHLdS9TEe-DGtHuJw_PQw" name="aprobar_rsuInput.aprobado" content="aprobar_rsuInput?.aprobado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_DHHLdi9TEe-DGtHuJw_PQw" name="aprobar_rsuInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_DHHLdy9TEe-DGtHuJw_PQw" type="JAVA_METHOD" expression="setAprobado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsiCAC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsiCAS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsiCAi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsiCAy5dEe-mJPIsZDPUkA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsiCBC5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xsiCBS5dEe-mJPIsZDPUkA">
            <targetForm xmi:type="expression:Expression" xmi:id="_xsiCBi5dEe-mJPIsZDPUkA" name="AprobarRsuEtica" content="816b0001-8d10-4140-b900-4d4fbeb87ca0" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xsiCBy5dEe-mJPIsZDPUkA">
            <inputs xmi:type="process:ContractInput" xmi:id="_Agu_EC9TEe-DGtHuJw_PQw" name="recibir_informacionInput" type="COMPLEX" dataReference="recibir_informacion" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Agu_ES9TEe-DGtHuJw_PQw" name="diagnostico" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Agu_Ei9TEe-DGtHuJw_PQw" name="informe" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Agu_Ey9TEe-DGtHuJw_PQw" name="pei" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_CFBcUC9TEe-DGtHuJw_PQw" name="elaborar_rsuInput" type="COMPLEX" dataReference="elaborar_rsu" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_CFBcUS9TEe-DGtHuJw_PQw" name="rsu" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_DHHLcC9TEe-DGtHuJw_PQw" name="aprobar_rsuInput" type="COMPLEX" dataReference="aprobar_rsu" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_DHHLcS9TEe-DGtHuJw_PQw" name="aprobado" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xsiCES5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_xsiBuC5dEe-mJPIsZDPUkA" name="Gateway" outgoing="_xsiCNC5dEe-mJPIsZDPUkA _n2FucC9LEe-DGtHuJw_PQw" incoming="_xsiCQy5dEe-mJPIsZDPUkA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsiBuS5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsiBui5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsiBuy5dEe-mJPIsZDPUkA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_mPeRwC9SEe-DGtHuJw_PQw" name="recibir_informacion" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.EntradasEtica">
        <defaultValue xmi:type="expression:Expression" xmi:id="_mPeRwS9SEe-DGtHuJw_PQw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_zUEwgC9SEe-DGtHuJw_PQw" name="elaborar_rsu" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.RSUEtica">
        <defaultValue xmi:type="expression:Expression" xmi:id="_zUEwgS9SEe-DGtHuJw_PQw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1w5_UC9SEe-DGtHuJw_PQw" name="aprobar_rsu" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_etica.ValidacionEtica">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1w5_US9SEe-DGtHuJw_PQw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_xsiCKi5dEe-mJPIsZDPUkA">
        <targetForm xmi:type="expression:Expression" xmi:id="_JRyeMDI2Ee-CdauvfITryg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_xsiCLC5dEe-mJPIsZDPUkA">
        <targetForm xmi:type="expression:Expression" xmi:id="_xsiCLS5dEe-mJPIsZDPUkA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCNC5dEe-mJPIsZDPUkA" name="no" target="_xsiBvC5dEe-mJPIsZDPUkA" source="_xsiBuC5dEe-mJPIsZDPUkA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCNS5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCNi5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCNy5dEe-mJPIsZDPUkA" target="_xsiBgS5dEe-mJPIsZDPUkA" source="_xsiBii5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCOC5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCOS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCOi5dEe-mJPIsZDPUkA" target="_xsiBji5dEe-mJPIsZDPUkA" source="_xsiBgS5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCOy5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCPC5dEe-mJPIsZDPUkA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCPS5dEe-mJPIsZDPUkA" target="_xsiBvC5dEe-mJPIsZDPUkA" source="_xsiBji5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCPi5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCPy5dEe-mJPIsZDPUkA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCQC5dEe-mJPIsZDPUkA" target="_xsiB2C5dEe-mJPIsZDPUkA" source="_xsiBvC5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCQS5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCQi5dEe-mJPIsZDPUkA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xsiCQy5dEe-mJPIsZDPUkA" name="¿Aprobacion del plan de RSU?" target="_xsiBuC5dEe-mJPIsZDPUkA" source="_xsiB2C5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xsiCRC5dEe-mJPIsZDPUkA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xsiCRS5dEe-mJPIsZDPUkA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n2FucC9LEe-DGtHuJw_PQw" name="si" target="_xsiCIC5dEe-mJPIsZDPUkA" source="_xsiBuC5dEe-mJPIsZDPUkA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n2IxwC9LEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_n2IxwS9LEe-DGtHuJw_PQw" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_xsiCSS5dEe-mJPIsZDPUkA" name="Director de Gestión Institucional"/>
      <actors xmi:type="process:Actor" xmi:id="_XzrpgC9FEe-DGtHuJw_PQw" name="Asistente de Gestión Institucional" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_pZwvYC9FEe-DGtHuJw_PQw" name="Coordinadora Administrativa"/>
      <contract xmi:type="process:Contract" xmi:id="_xsiCTC5dEe-mJPIsZDPUkA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiCTS5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiCTi5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiCTy5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiCUC5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiCUS5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiCUi5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiCUy5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiCVC5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiCVS5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiCVi5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiCVy5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiCWC5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_xsiCWS5dEe-mJPIsZDPUkA">
        <name xmi:type="expression:Expression" xmi:id="_xsiCWi5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_xsiCWy5dEe-mJPIsZDPUkA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_ZWGaUC9MEe-DGtHuJw_PQw" name="PM03.01.02">
      <elements xmi:type="process:Lane" xmi:id="_cmhpQC9MEe-DGtHuJw_PQw" name="Asistente de Gestión Institucional" actor="_0ERtIC9MEe-DGtHuJw_PQw">
        <elements xmi:type="process:StartEvent" xmi:id="_whvagC9MEe-DGtHuJw_PQw" name="Inicio del proceso" outgoing="_59NPYC9MEe-DGtHuJw_PQw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_whvagS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_whvagi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_whvagy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_zdMfAC9MEe-DGtHuJw_PQw" name="Recibir solicitud" outgoing="_6df5AC9MEe-DGtHuJw_PQw" incoming="_59NPYC9MEe-DGtHuJw_PQw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zdMfAS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zdMfAi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zdMfAy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zdMfBC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zdMfBS9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zdMfBi9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zdMfBy9MEe-DGtHuJw_PQw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zdMfCC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0ESUMC9MEe-DGtHuJw_PQw" name="Recibir el Plan Anual RSU" outgoing="_AfNj0C9NEe-DGtHuJw_PQw" incoming="_6df5AC9MEe-DGtHuJw_PQw" actor="_0ERtIC9MEe-DGtHuJw_PQw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0ESUMS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0ESUMi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0ESUMy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_FwAAMjI7Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FwAAMzI7Ee-CdauvfITryg" name="entradaDesarrollo" content="entradaDesarrollo" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.EntradaDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FwAANDI7Ee-CdauvfITryg" name="entradaDesarrollo" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.EntradaDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FwAANTI7Ee-CdauvfITryg" name="entradaDesarrolloInput.rsu" content="entradaDesarrolloInput?.rsu" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FwAANjI7Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FwAANzI7Ee-CdauvfITryg" type="JAVA_METHOD" expression="setRsu">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0ESUQC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0ESUQS9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0ESUQi9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0ESUQy9MEe-DGtHuJw_PQw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0ESURC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0ESURS9MEe-DGtHuJw_PQw">
            <targetForm xmi:type="expression:Expression" xmi:id="_0ESURi9MEe-DGtHuJw_PQw" name="recibirPlanAnual" content="453a7286-d99a-45a3-8c17-df987b5c6369" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0ESURy9MEe-DGtHuJw_PQw">
            <inputs xmi:type="process:ContractInput" xmi:id="_FwAAMDI7Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" dataReference="entradaDesarrollo" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_FwAAMTI7Ee-CdauvfITryg" name="rsu" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0ESUSy9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_c4zFAC9MEe-DGtHuJw_PQw" name="Coordinadora Administrativa" actor="_jV32IC9MEe-DGtHuJw_PQw">
        <elements xmi:type="process:Task" xmi:id="_0oLrcC9MEe-DGtHuJw_PQw" name="Planificar Actividades para Mayor Satisfacción y Mejor Clima Laboral" outgoing="_FIRZoC9NEe-DGtHuJw_PQw" incoming="_AfNj0C9NEe-DGtHuJw_PQw _JvzlcC9NEe-DGtHuJw_PQw" actor="_jV32IC9MEe-DGtHuJw_PQw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0oLrcS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0oLrci9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0oLrcy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_awuA8jI7Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_awuA8zI7Ee-CdauvfITryg" name="entradaDesarrollo" content="entradaDesarrollo" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.EntradaDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_awuA9DI7Ee-CdauvfITryg" name="entradaDesarrollo" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.EntradaDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_awuA9TI7Ee-CdauvfITryg" name="entradaDesarrolloInput.rsu" content="entradaDesarrolloInput?.rsu" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_awuA9jI7Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_awuA9zI7Ee-CdauvfITryg" type="JAVA_METHOD" expression="setRsu">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_GptkgzI9Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_GptkhDI9Ee-CdauvfITryg" name="procesoPlanificar" content="procesoPlanificar" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.PlanificarDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_GptkhTI9Ee-CdauvfITryg" name="procesoPlanificar" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.PlanificarDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GptkhjI9Ee-CdauvfITryg" name="procesoPlanificarInput.planificacion" content="procesoPlanificarInput?.planificacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_GptkhzI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_GptkiDI9Ee-CdauvfITryg" type="JAVA_METHOD" expression="setPlanificacion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_GptkiTI9Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_GptkijI9Ee-CdauvfITryg" name="procesoPlanificar" content="procesoPlanificar" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.PlanificarDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_GptkizI9Ee-CdauvfITryg" name="procesoPlanificar" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.PlanificarDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GptkjDI9Ee-CdauvfITryg" name="procesoPlanificarInput.aprobar" content="procesoPlanificarInput?.aprobar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_GptkjTI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_GptkjjI9Ee-CdauvfITryg" type="JAVA_METHOD" expression="setAprobar">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0oLrgC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0oLrgS9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0oLrgi9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0oLrgy9MEe-DGtHuJw_PQw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0oLrhC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0oLrhS9MEe-DGtHuJw_PQw">
            <targetForm xmi:type="expression:Expression" xmi:id="_0oLrhi9MEe-DGtHuJw_PQw" name="planificarRSU" content="6f5c81ec-cb29-46c5-98df-2759e14f3df1" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0oLrhy9MEe-DGtHuJw_PQw">
            <inputs xmi:type="process:ContractInput" xmi:id="_awuA8DI7Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" dataReference="entradaDesarrollo" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_awuA8TI7Ee-CdauvfITryg" name="rsu" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_GptkgDI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" dataReference="procesoPlanificar" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_GptkgTI9Ee-CdauvfITryg" name="planificacion" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_GptkgjI9Ee-CdauvfITryg" name="aprobar" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0oLriy9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_dPDo4C9MEe-DGtHuJw_PQw" name="Director de Gestion Institucional" actor="_JOXvEDI8Ee-CdauvfITryg">
        <elements xmi:type="process:Task" xmi:id="_1sUpAC9MEe-DGtHuJw_PQw" name="Generar el Informe Anual de RSU" outgoing="_QlcAgC9NEe-DGtHuJw_PQw" incoming="_NRhYsC9NEe-DGtHuJw_PQw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1sUpAS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1sUpAi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1sUpAy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_aD46sjI8Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_aD46szI8Ee-CdauvfITryg" name="entradaDesarrollo" content="entradaDesarrollo" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.EntradaDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_aD46tDI8Ee-CdauvfITryg" name="entradaDesarrollo" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.EntradaDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_aD46tTI8Ee-CdauvfITryg" name="entradaDesarrolloInput.rsu" content="entradaDesarrolloInput?.rsu" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_aD46tjI8Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_aD46tzI8Ee-CdauvfITryg" type="JAVA_METHOD" expression="setRsu">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_cYcXQjI8Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cYcXQzI8Ee-CdauvfITryg" name="informeFinal" content="informeFinal" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.InformeRSU">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_cYcXRDI8Ee-CdauvfITryg" name="informeFinal" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.InformeRSU"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cYcXRTI8Ee-CdauvfITryg" name="informeFinalInput.rsufinal" content="informeFinalInput?.rsufinal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_cYcXRjI8Ee-CdauvfITryg" name="informeFinalInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cYcXRzI8Ee-CdauvfITryg" type="JAVA_METHOD" expression="setRsufinal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_bCUcYzI9Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_bCUcZDI9Ee-CdauvfITryg" name="procesoPlanificar" content="procesoPlanificar" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.PlanificarDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bCUcZTI9Ee-CdauvfITryg" name="procesoPlanificar" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.PlanificarDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_bCUcZjI9Ee-CdauvfITryg" name="procesoPlanificarInput.planificacion" content="procesoPlanificarInput?.planificacion" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_bCUcZzI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_bCUcaDI9Ee-CdauvfITryg" type="JAVA_METHOD" expression="setPlanificacion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_bCUcaTI9Ee-CdauvfITryg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_bCUcajI9Ee-CdauvfITryg" name="procesoPlanificar" content="procesoPlanificar" type="TYPE_VARIABLE" returnType="com.dex.gestion_desarrollo.PlanificarDesarrollo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bCUcazI9Ee-CdauvfITryg" name="procesoPlanificar" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.PlanificarDesarrollo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_bCUcbDI9Ee-CdauvfITryg" name="procesoPlanificarInput.aprobar" content="procesoPlanificarInput?.aprobar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_bCUcbTI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_bCUcbjI9Ee-CdauvfITryg" type="JAVA_METHOD" expression="setAprobar">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1sUpKC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1sUpKS9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1sUpKi9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1sUpKy9MEe-DGtHuJw_PQw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1sUpLC9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_1sUpLS9MEe-DGtHuJw_PQw">
            <targetForm xmi:type="expression:Expression" xmi:id="_1sUpLi9MEe-DGtHuJw_PQw" name="finalRSU" content="ac1afcfd-0310-427c-aeaf-fa396ea3a677" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_1sUpLy9MEe-DGtHuJw_PQw">
            <inputs xmi:type="process:ContractInput" xmi:id="_aD46sDI8Ee-CdauvfITryg" name="entradaDesarrolloInput" type="COMPLEX" dataReference="entradaDesarrollo" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_aD46sTI8Ee-CdauvfITryg" name="rsu" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_cYcXQDI8Ee-CdauvfITryg" name="informeFinalInput" type="COMPLEX" dataReference="informeFinal" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cYcXQTI8Ee-CdauvfITryg" name="rsufinal" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_bCUcYDI9Ee-CdauvfITryg" name="procesoPlanificarInput" type="COMPLEX" dataReference="procesoPlanificar" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_bCUcYTI9Ee-CdauvfITryg" name="planificacion" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_bCUcYjI9Ee-CdauvfITryg" name="aprobar" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_1sUpOS9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_2OuygC9MEe-DGtHuJw_PQw" name="Cópia de Gateway" outgoing="_JvzlcC9NEe-DGtHuJw_PQw _NRhYsC9NEe-DGtHuJw_PQw" incoming="_FIRZoC9NEe-DGtHuJw_PQw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2OuygS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2Ouygi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2Ouygy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_2u8joC9MEe-DGtHuJw_PQw" name="Fin del proceso" incoming="_QlcAgC9NEe-DGtHuJw_PQw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2u8joS9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2u8joi9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2u8joy9MEe-DGtHuJw_PQw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_78iiEDI6Ee-CdauvfITryg" name="entradaDesarrollo" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.EntradaDesarrollo">
        <defaultValue xmi:type="expression:Expression" xmi:id="_78iiETI6Ee-CdauvfITryg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_9r_tgDI6Ee-CdauvfITryg" name="informeFinal" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.InformeRSU">
        <defaultValue xmi:type="expression:Expression" xmi:id="_9r_tgTI6Ee-CdauvfITryg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="__LcHADI6Ee-CdauvfITryg" name="procesoPlanificar" dataType="_xsiC_C5dEe-mJPIsZDPUkA" className="com.dex.gestion_desarrollo.PlanificarDesarrollo">
        <defaultValue xmi:type="expression:Expression" xmi:id="__LcHATI6Ee-CdauvfITryg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ZZN_zy9MEe-DGtHuJw_PQw">
        <targetForm xmi:type="expression:Expression" xmi:id="_E0HZADI2Ee-CdauvfITryg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ZZOm0C9MEe-DGtHuJw_PQw">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZZOm0S9MEe-DGtHuJw_PQw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_59NPYC9MEe-DGtHuJw_PQw" target="_zdMfAC9MEe-DGtHuJw_PQw" source="_whvagC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_59NPYS9MEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_59NPYi9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6df5AC9MEe-DGtHuJw_PQw" target="_0ESUMC9MEe-DGtHuJw_PQw" source="_zdMfAC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6df5AS9MEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_6df5Ai9MEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AfNj0C9NEe-DGtHuJw_PQw" target="_0oLrcC9MEe-DGtHuJw_PQw" source="_0ESUMC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AfOK4C9NEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_AfOK4S9NEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FIRZoC9NEe-DGtHuJw_PQw" name="Se Implemento Correctamente?" target="_2OuygC9MEe-DGtHuJw_PQw" source="_0oLrcC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FIRZoS9NEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_FIRZoi9NEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JvzlcC9NEe-DGtHuJw_PQw" name="no" target="_0oLrcC9MEe-DGtHuJw_PQw" source="_2OuygC9MEe-DGtHuJw_PQw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JvzlcS9NEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Jvzlci9NEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NRhYsC9NEe-DGtHuJw_PQw" name="si" target="_1sUpAC9MEe-DGtHuJw_PQw" source="_2OuygC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NRhYsS9NEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NRhYsi9NEe-DGtHuJw_PQw" name="True" content="True" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QlcAgC9NEe-DGtHuJw_PQw" target="_2u8joC9MEe-DGtHuJw_PQw" source="_1sUpAC9MEe-DGtHuJw_PQw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QlcAgS9NEe-DGtHuJw_PQw"/>
        <condition xmi:type="expression:Expression" xmi:id="_QlcAgi9NEe-DGtHuJw_PQw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_jV32IC9MEe-DGtHuJw_PQw" name="Coordinadora Administrativa"/>
      <actors xmi:type="process:Actor" xmi:id="_0ERtIC9MEe-DGtHuJw_PQw" name="Asistente de Gestión Institucional" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_JOXvEDI8Ee-CdauvfITryg" name="Director de Gestión Institucional"/>
      <contract xmi:type="process:Contract" xmi:id="_ZZOm0i9MEe-DGtHuJw_PQw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZZN_wC9MEe-DGtHuJw_PQw">
        <name xmi:type="expression:Expression" xmi:id="_ZZN_wS9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZZN_wi9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZZN_wy9MEe-DGtHuJw_PQw">
        <name xmi:type="expression:Expression" xmi:id="_ZZN_xC9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZZN_xS9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZZN_xi9MEe-DGtHuJw_PQw">
        <name xmi:type="expression:Expression" xmi:id="_ZZN_xy9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZZN_yC9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZZN_yS9MEe-DGtHuJw_PQw">
        <name xmi:type="expression:Expression" xmi:id="_ZZN_yi9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZZN_yy9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZZN_zC9MEe-DGtHuJw_PQw">
        <name xmi:type="expression:Expression" xmi:id="_ZZN_zS9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZZN_zi9MEe-DGtHuJw_PQw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_xsiC9C5dEe-mJPIsZDPUkA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_xsiC9S5dEe-mJPIsZDPUkA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_xsiC9i5dEe-mJPIsZDPUkA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_xsiC9y5dEe-mJPIsZDPUkA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_xsiC-C5dEe-mJPIsZDPUkA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_xsiC-S5dEe-mJPIsZDPUkA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_xsiC-i5dEe-mJPIsZDPUkA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_xsiC-y5dEe-mJPIsZDPUkA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_xsiC_C5dEe-mJPIsZDPUkA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_xsiC_S5dEe-mJPIsZDPUkA" type="Process" element="_xsiBQC5dEe-mJPIsZDPUkA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_xsiC_i5dEe-mJPIsZDPUkA" type="2007" element="_xsiBQS5dEe-mJPIsZDPUkA">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiC_y5dEe-mJPIsZDPUkA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDAC5dEe-mJPIsZDPUkA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_xsiDAS5dEe-mJPIsZDPUkA" type="3007" element="_xsiBQi5dEe-mJPIsZDPUkA">
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDAi5dEe-mJPIsZDPUkA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDAy5dEe-mJPIsZDPUkA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xsiDBC5dEe-mJPIsZDPUkA" type="3002" element="_xsiBQy5dEe-mJPIsZDPUkA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDBS5dEe-mJPIsZDPUkA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDBi5dEe-mJPIsZDPUkA" x="3" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDBy5dEe-mJPIsZDPUkA" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDCC5dEe-mJPIsZDPUkA" type="3063" element="_xsiBRy5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDCS5dEe-mJPIsZDPUkA" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDCi5dEe-mJPIsZDPUkA" x="232" y="97" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDCy5dEe-mJPIsZDPUkA" type="3063" element="_xsiBUi5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDDC5dEe-mJPIsZDPUkA" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDDS5dEe-mJPIsZDPUkA" x="494" y="85" width="224" height="112"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDDi5dEe-mJPIsZDPUkA" type="3003" element="_xsiBXS5dEe-mJPIsZDPUkA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDDy5dEe-mJPIsZDPUkA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDEC5dEe-mJPIsZDPUkA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDES5dEe-mJPIsZDPUkA" x="850" y="154"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDEi5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xsiDEy5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xsiDFC5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xsiDFS5dEe-mJPIsZDPUkA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDFi5dEe-mJPIsZDPUkA" x="48" y="10" width="1227" height="267"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDFy5dEe-mJPIsZDPUkA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDGC5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_xsiDGS5dEe-mJPIsZDPUkA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_xsiDGi5dEe-mJPIsZDPUkA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDGy5dEe-mJPIsZDPUkA" width="1250" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_xsiDHC5dEe-mJPIsZDPUkA" type="2007" element="_xsiBfy5dEe-mJPIsZDPUkA">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDHS5dEe-mJPIsZDPUkA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDHi5dEe-mJPIsZDPUkA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_xsiDHy5dEe-mJPIsZDPUkA" type="3007" element="_xsiBgC5dEe-mJPIsZDPUkA">
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDIC5dEe-mJPIsZDPUkA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDIS5dEe-mJPIsZDPUkA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xsiDIi5dEe-mJPIsZDPUkA" type="3027" element="_xsiBgS5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDIy5dEe-mJPIsZDPUkA" type="5017" element="_xsiBgS5dEe-mJPIsZDPUkA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDJC5dEe-mJPIsZDPUkA" x="148" y="55" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDJS5dEe-mJPIsZDPUkA" type="3002" element="_xsiBii5dEe-mJPIsZDPUkA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDJi5dEe-mJPIsZDPUkA" type="5024" element="_xsiBii5dEe-mJPIsZDPUkA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDJy5dEe-mJPIsZDPUkA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDKC5dEe-mJPIsZDPUkA" x="60" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDKS5dEe-mJPIsZDPUkA" type="3005" element="_xsiBji5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDKi5dEe-mJPIsZDPUkA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDKy5dEe-mJPIsZDPUkA" x="368" y="56" width="192" height="96"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDLC5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xsiDLS5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xsiDLi5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xsiDLy5dEe-mJPIsZDPUkA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDMC5dEe-mJPIsZDPUkA" x="50" y="10" width="1211" height="235"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_xsiDMS5dEe-mJPIsZDPUkA" type="3007" element="_xsiBqi5dEe-mJPIsZDPUkA">
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDMi5dEe-mJPIsZDPUkA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDMy5dEe-mJPIsZDPUkA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xsiDOy5dEe-mJPIsZDPUkA" type="3005" element="_xsiBvC5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDPC5dEe-mJPIsZDPUkA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDPS5dEe-mJPIsZDPUkA" x="209" y="63" width="189" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDQS5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xsiDQi5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xsiDQy5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xsiDRC5dEe-mJPIsZDPUkA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDRS5dEe-mJPIsZDPUkA" x="50" y="235" width="1211" height="220"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_xsiDRi5dEe-mJPIsZDPUkA" type="3007" element="_xsiCEi5dEe-mJPIsZDPUkA">
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDRy5dEe-mJPIsZDPUkA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xsiDSC5dEe-mJPIsZDPUkA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_xsiDTC5dEe-mJPIsZDPUkA" type="3003" element="_xsiCIC5dEe-mJPIsZDPUkA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDTS5dEe-mJPIsZDPUkA" type="5025" element="_xsiCIC5dEe-mJPIsZDPUkA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDTi5dEe-mJPIsZDPUkA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDTy5dEe-mJPIsZDPUkA" x="1087" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDPi5dEe-mJPIsZDPUkA" type="3005" element="_xsiB2C5dEe-mJPIsZDPUkA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDPy5dEe-mJPIsZDPUkA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDQC5dEe-mJPIsZDPUkA" x="329" y="50" width="215" height="107"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xsiDNy5dEe-mJPIsZDPUkA" type="3008" element="_xsiBuC5dEe-mJPIsZDPUkA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_xsiDOC5dEe-mJPIsZDPUkA" visible="false" type="5026" element="_xsiBuC5dEe-mJPIsZDPUkA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDOS5dEe-mJPIsZDPUkA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDOi5dEe-mJPIsZDPUkA" x="783" y="50" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDUC5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xsiDUS5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xsiDUi5dEe-mJPIsZDPUkA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xsiDUy5dEe-mJPIsZDPUkA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDVC5dEe-mJPIsZDPUkA" x="50" y="512" width="1211" height="217"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_xsiDVS5dEe-mJPIsZDPUkA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDVi5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_xsiDVy5dEe-mJPIsZDPUkA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_xsiDWC5dEe-mJPIsZDPUkA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xsiDWS5dEe-mJPIsZDPUkA" width="1236" height="474"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ZZP08C9MEe-DGtHuJw_PQw" type="2007" element="_ZWGaUC9MEe-DGtHuJw_PQw">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZZP09S9MEe-DGtHuJw_PQw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ZZP09i9MEe-DGtHuJw_PQw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_cmiQUC9MEe-DGtHuJw_PQw" type="3007" element="_cmhpQC9MEe-DGtHuJw_PQw">
          <children xmi:type="notation:DecorationNode" xmi:id="_cmiQVS9MEe-DGtHuJw_PQw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_cmiQVi9MEe-DGtHuJw_PQw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_whvahC9MEe-DGtHuJw_PQw" type="3002" element="_whvagC9MEe-DGtHuJw_PQw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_whvahS9MEe-DGtHuJw_PQw" type="5024" element="_whvagC9MEe-DGtHuJw_PQw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_whvahi9MEe-DGtHuJw_PQw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_whvahy9MEe-DGtHuJw_PQw" x="86" y="95"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zdMfCS9MEe-DGtHuJw_PQw" type="3027" element="_zdMfAC9MEe-DGtHuJw_PQw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zdMfCi9MEe-DGtHuJw_PQw" type="5017" element="_zdMfAC9MEe-DGtHuJw_PQw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zdMfCy9MEe-DGtHuJw_PQw" x="208" y="78" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0ESUTC9MEe-DGtHuJw_PQw" type="3005" element="_0ESUMC9MEe-DGtHuJw_PQw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0ESUTS9MEe-DGtHuJw_PQw" type="5005" element="_0ESUMC9MEe-DGtHuJw_PQw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0ESUTi9MEe-DGtHuJw_PQw" x="422" y="62" width="192" height="96"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_cmiQUS9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_cmiQUi9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_cmiQUy9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_cmiQVy9MEe-DGtHuJw_PQw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cmiQVC9MEe-DGtHuJw_PQw" x="53" y="10" width="1292" height="216"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_c4zsEC9MEe-DGtHuJw_PQw" type="3007" element="_c4zFAC9MEe-DGtHuJw_PQw">
          <children xmi:type="notation:DecorationNode" xmi:id="_c4zsFS9MEe-DGtHuJw_PQw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_c4zsFi9MEe-DGtHuJw_PQw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0oLrjC9MEe-DGtHuJw_PQw" type="3005" element="_0oLrcC9MEe-DGtHuJw_PQw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0oLrjS9MEe-DGtHuJw_PQw" type="5005" element="_0oLrcC9MEe-DGtHuJw_PQw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0oLrji9MEe-DGtHuJw_PQw" x="402" y="49" width="189" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_c4zsES9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_c4zsEi9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_c4zsEy9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_c4zsFy9MEe-DGtHuJw_PQw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c4zsFC9MEe-DGtHuJw_PQw" x="53" y="216" width="1292" height="240"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_dPEP8C9MEe-DGtHuJw_PQw" type="3007" element="_dPDo4C9MEe-DGtHuJw_PQw">
          <children xmi:type="notation:DecorationNode" xmi:id="_dPEP9S9MEe-DGtHuJw_PQw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_dPEP9i9MEe-DGtHuJw_PQw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_1sUpOi9MEe-DGtHuJw_PQw" type="3005" element="_1sUpAC9MEe-DGtHuJw_PQw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1sUpOy9MEe-DGtHuJw_PQw" type="5005" element="_1sUpAC9MEe-DGtHuJw_PQw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1sUpPC9MEe-DGtHuJw_PQw" x="694" y="71" width="215" height="107"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2OuyhC9MEe-DGtHuJw_PQw" type="3008" element="_2OuygC9MEe-DGtHuJw_PQw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_2OuyhS9MEe-DGtHuJw_PQw" visible="false" type="5026" element="_2OuygC9MEe-DGtHuJw_PQw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2Ouyhi9MEe-DGtHuJw_PQw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2Ouyhy9MEe-DGtHuJw_PQw" x="475" y="103" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2u8jpC9MEe-DGtHuJw_PQw" type="3003" element="_2u8joC9MEe-DGtHuJw_PQw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_2u8jpS9MEe-DGtHuJw_PQw" type="5025" element="_2u8joC9MEe-DGtHuJw_PQw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2u8jpi9MEe-DGtHuJw_PQw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2u8jpy9MEe-DGtHuJw_PQw" x="1099" y="110"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_dPEP8S9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_dPEP8i9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_dPEP8y9MEe-DGtHuJw_PQw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_dPEP9y9MEe-DGtHuJw_PQw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dPEP9C9MEe-DGtHuJw_PQw" x="53" y="456" width="1292" height="240"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZZP08S9MEe-DGtHuJw_PQw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZZP08i9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ZZP08y9MEe-DGtHuJw_PQw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ZZP09y9MEe-DGtHuJw_PQw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZZP09C9MEe-DGtHuJw_PQw" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_xsiDpC5dEe-mJPIsZDPUkA"/>
    <edges xmi:type="notation:Connector" xmi:id="_xsiDpS5dEe-mJPIsZDPUkA" type="4001" element="_xsiBZS5dEe-mJPIsZDPUkA" source="_xsiDBC5dEe-mJPIsZDPUkA" target="_xsiDCC5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDpi5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDpy5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDqC5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiDqS5dEe-mJPIsZDPUkA" points="[-8, -3, -226, -65]$[212, 100, -6, 38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiDqi5dEe-mJPIsZDPUkA" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiDqy5dEe-mJPIsZDPUkA" type="4001" element="_xsiBaC5dEe-mJPIsZDPUkA" source="_xsiDCC5dEe-mJPIsZDPUkA" target="_xsiDCy5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDrC5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDrS5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDri5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiDry5dEe-mJPIsZDPUkA" points="[0, 9, -256, 0]$[294, 18, 38, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiDsC5dEe-mJPIsZDPUkA" id="(1.0,0.39473684210526316)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiDsS5dEe-mJPIsZDPUkA" id="(0.7888888888888889,0.6444444444444445)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiDsi5dEe-mJPIsZDPUkA" type="4001" element="_xsiBay5dEe-mJPIsZDPUkA" source="_xsiDCy5dEe-mJPIsZDPUkA" target="_xsiDDi5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDsy5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDtC5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDtS5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiDti5dEe-mJPIsZDPUkA" points="[0, 0, -187, -35]$[185, 20, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiDty5dEe-mJPIsZDPUkA" id="(1.0,0.34444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiDwy5dEe-mJPIsZDPUkA" type="4001" element="_xsiCNC5dEe-mJPIsZDPUkA" source="_xsiDNy5dEe-mJPIsZDPUkA" target="_xsiDOy5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDxC5dEe-mJPIsZDPUkA" type="6001" element="_xsiCNC5dEe-mJPIsZDPUkA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDxS5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDxi5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiDxy5dEe-mJPIsZDPUkA" points="[-22, -28, 431, 211]$[-22, -236, 431, 3]$[-428, -236, 25, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiDyC5dEe-mJPIsZDPUkA" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tOAOUC9LEe-DGtHuJw_PQw" id="(0.8677248677248677,0.46808510638297873)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiDyS5dEe-mJPIsZDPUkA" type="4001" element="_xsiCNy5dEe-mJPIsZDPUkA" source="_xsiDJS5dEe-mJPIsZDPUkA" target="_xsiDIi5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiDyi5dEe-mJPIsZDPUkA" type="6001" element="_xsiCNy5dEe-mJPIsZDPUkA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiDyy5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiDzC5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiDzS5dEe-mJPIsZDPUkA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiEDy5dEe-mJPIsZDPUkA" type="4001" element="_xsiCOi5dEe-mJPIsZDPUkA" source="_xsiDIi5dEe-mJPIsZDPUkA" target="_xsiDKS5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiEEC5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiEES5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiEEi5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiEEy5dEe-mJPIsZDPUkA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiEFC5dEe-mJPIsZDPUkA" type="4001" element="_xsiCPS5dEe-mJPIsZDPUkA" source="_xsiDKS5dEe-mJPIsZDPUkA" target="_xsiDOy5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiEFS5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiEFi5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiEFy5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiEGC5dEe-mJPIsZDPUkA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiEGS5dEe-mJPIsZDPUkA" type="4001" element="_xsiCQC5dEe-mJPIsZDPUkA" source="_xsiDOy5dEe-mJPIsZDPUkA" target="_xsiDPi5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiEGi5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiEGy5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiEHC5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiEHS5dEe-mJPIsZDPUkA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xsiEHi5dEe-mJPIsZDPUkA" type="4001" element="_xsiCQy5dEe-mJPIsZDPUkA" source="_xsiDPi5dEe-mJPIsZDPUkA" target="_xsiDNy5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xsiEHy5dEe-mJPIsZDPUkA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xsiEIC5dEe-mJPIsZDPUkA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xsiEIS5dEe-mJPIsZDPUkA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xsiEIi5dEe-mJPIsZDPUkA" points="[-60, 25, -309, 60]$[-60, 41, -309, 76]$[115, 41, -134, 76]$[115, -32, -134, 3]$[230, -32, -19, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xsiEIy5dEe-mJPIsZDPUkA" id="(1.0,0.5833333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n2SiwC9LEe-DGtHuJw_PQw" type="4001" element="_n2FucC9LEe-DGtHuJw_PQw" source="_xsiDNy5dEe-mJPIsZDPUkA" target="_xsiDTC5dEe-mJPIsZDPUkA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n2TJ0C9LEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n2TJ0S9LEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n2SiwS9LEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n2Siwi9LEe-DGtHuJw_PQw" points="[-12, 5, -288, 0]$[276, 5, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n2UX8C9LEe-DGtHuJw_PQw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_59NPYy9MEe-DGtHuJw_PQw" type="4001" element="_59NPYC9MEe-DGtHuJw_PQw" source="_whvahC9MEe-DGtHuJw_PQw" target="_zdMfCS9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_59NPZi9MEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_59NPZy9MEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_59NPZC9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_59NPZS9MEe-DGtHuJw_PQw" points="[-7, -2, -137, -30]$[66, 20, -64, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_59OdgC9MEe-DGtHuJw_PQw" id="(1.0,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6df5Ay9MEe-DGtHuJw_PQw" type="4001" element="_6df5AC9MEe-DGtHuJw_PQw" source="_zdMfCS9MEe-DGtHuJw_PQw" target="_0ESUTC9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6dggEC9MEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6dggES9MEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6df5BC9MEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6df5BS9MEe-DGtHuJw_PQw" points="[0, 0, -200, -82]$[166, 83, -34, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6dhHIC9MEe-DGtHuJw_PQw" id="(1.0,0.4375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6dhHIS9MEe-DGtHuJw_PQw" id="(0.17708333333333334,0.53125)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AfOK4i9NEe-DGtHuJw_PQw" type="4001" element="_AfNj0C9NEe-DGtHuJw_PQw" source="_0ESUTC9MEe-DGtHuJw_PQw" target="_0oLrjC9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AfOx8C9NEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AfOx8S9NEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AfOK4y9NEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AfOK5C9NEe-DGtHuJw_PQw" points="[-100, 63, 18, -248]$[-100, 264, 18, -47]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AfPZAC9NEe-DGtHuJw_PQw" id="(1.0,0.34375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FIRZoy9NEe-DGtHuJw_PQw" type="4001" element="_FIRZoC9NEe-DGtHuJw_PQw" source="_0oLrjC9MEe-DGtHuJw_PQw" target="_2OuyhC9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FISAsC9NEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FISAsS9NEe-DGtHuJw_PQw" x="27" y="-11"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FIRZpC9NEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FIRZpS9NEe-DGtHuJw_PQw" points="[-95, 66, 0, -231]$[-95, 276, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FISnwC9NEe-DGtHuJw_PQw" id="(1.0,0.2978723404255319)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Jvzlcy9NEe-DGtHuJw_PQw" type="4001" element="_JvzlcC9NEe-DGtHuJw_PQw" source="_2OuyhC9MEe-DGtHuJw_PQw" target="_0oLrjC9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jvzldi9NEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jvzldy9NEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JvzldC9NEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JvzldS9NEe-DGtHuJw_PQw" points="[-43, -10, -85, 276]$[-168, -10, -210, 276]$[-168, -288, -210, -2]$[-116, -288, -158, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jv0MgC9NEe-DGtHuJw_PQw" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jv0MgS9NEe-DGtHuJw_PQw" id="(0.8359788359788359,0.5212765957446809)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NRlqIC9NEe-DGtHuJw_PQw" type="4001" element="_NRhYsC9NEe-DGtHuJw_PQw" source="_2OuyhC9MEe-DGtHuJw_PQw" target="_1sUpOi9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NRlqIy9NEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NRlqJC9NEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NRlqIS9NEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NRlqIi9NEe-DGtHuJw_PQw" points="[-8, 0, -351, 7]$[236, -10, -107, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NRmRMC9NEe-DGtHuJw_PQw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QlcAgy9NEe-DGtHuJw_PQw" type="4001" element="_QlcAgC9NEe-DGtHuJw_PQw" source="_1sUpOi9MEe-DGtHuJw_PQw" target="_2u8jpC9MEe-DGtHuJw_PQw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QlcAhi9NEe-DGtHuJw_PQw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QlcAhy9NEe-DGtHuJw_PQw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QlcAhC9NEe-DGtHuJw_PQw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QlcAhS9NEe-DGtHuJw_PQw" points="[0, 25, -205, -2]$[190, 25, -15, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QlcAiC9NEe-DGtHuJw_PQw" id="(1.0,0.2523364485981308)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
